### ISSUE TITLE
[FIRApp configure] could not find a valid GoogleServices-Info.plist in your project.

### ISSUE THREAD

**Issue by mirkos93** [fechanique/cordova-plugin-fcm#100]
Hi all,
i'm compiling my first Ionic app with FCM support under iOS and i would do this without use xCode, I would do it all from the command line.
Currently, however, it would seem that, when starting the app, the app can not find the plist file provided by Firebase. How can I solve this problem?

Thank you
Mirko

**Comment by erinsasha** [comment]
Hi!
I have the same issue, but with pure Cordova and xCode.

**Comment by aparedes** [comment]
You have to add your GoogleServices-Info.plist file manually to Xcode

**Comment by mirkos93** [comment]
@aparedes no other solution to this problem? Is possible to access the directory which access xCode using bash?

Thank you
Mirko

**Comment by aparedes** [comment]
@mirkos93 PR #92 solves the issue, I have not tried it myself but should work.

The thing is that you have to add the file also to some configuration files. It can be done with bash, but it is quicker to just open Xcode and set the file there.

**Comment by mirkos93** [comment]
@aparedes Thank you! I will try between 2-3 hours and let you know.

**Comment by mirkos93** [comment]
@aparedes Hello, i've applied the patch in the pull request but unfortunately the app always crashes with the same error.

> The thing is that you have to add the file also to some configuration files. It can be done with bash, but it is quicker to just open Xcode and set the file there.
Can you give me specific inherent to this thing?

Thank you
Mirko

**Comment by aparedes** [comment]
You have to add the GoogleService-Info.plist to the project.pbxproj file. There are several tools to help you do that or using node there is one called node-xcode. You could probably do a after-prepare script hook to do that for you.

**Comment by mirkos93** [comment]
Hi, 
thank you so much for your support, luckily it seems that the pull request #92 is working correctly!
For everyone facing the same issue, I recommend:
1- Apply the patch of pull request #92 
2- Check that the file name matches: "GoogleService-Info.plist" (non-GoogleServices-Info.plis (pay attention tho the extra "s"))
3- Run:
remove ionic platform ios
ionic platform add ios

Thanks again for the support
Mirko
