### ISSUE TITLE
Set Notification background color Android

### ISSUE THREAD

**Issue by francois-n-dream** [fechanique/cordova-plugin-fcm#105]
Is there a way to set the background color of the notification on Android?

Showing the icon works perfectly but I want to have a different background color.

I saw that ``notificationBuilder`` has a method ``setColor(ARGB)``. I tried to manually add this method, but it did not work (probably I am doing it in the wrong place).

**Comment by prabhulalramesh** [comment]
@francois-n-dream  Hi i have successfully integrated the fcm plugin. But i am not getting the icon in the notification tray. I have tried many things , nothing is working for fcm_push_icon

**Comment by prabhulalramesh** [comment]
@francois-n-dream to set the notification icon background color you just need to pass a key as "color":#RRGGBB format. Check the android key references in this link https://firebase.google.com/docs/cloud-messaging/http-server-ref  It worked for me. Ask me if any help required. BTW i did using Ionic and cordova framework

**Comment by francois-n-dream** [comment]
@prabhulalramesh thanks! 

I simply added the icon as png file in the ``platforms/android/res/`` directories (like drawable-hdpi) and named it ``fcm_push_icon.png``.

**Comment by joesleiman** [comment]
but how to change the background color of the app? as it is necessary to be transparent background when u generate many one and put them in directories in res folders.?
