### ISSUE TITLE
Background push not working on iOS 10

### ISSUE THREAD

**Issue by jorchg** [fechanique/cordova-plugin-fcm#118]
When I update from iOS 9 to iOS 10 the background pushes are not triggering the onNotification callback, so when entering in foreground the push is not triggering anything.

I have created a pull request with a 5 min fix: https://github.com/fechanique/cordova-plugin-fcm/pull/117

**Comment by benny1308** [comment]
Please @fechanique merge this pull request and the analytics pr as well. Your plugin is great, but needs your attention. Thank you!

**Comment by belliAndrea** [comment]
pls merge this!!

**Comment by fechanique** [comment]
I'm going to review it!

2016-10-01 12:33 GMT+02:00 Andrea <notifications@github.com>:

**Comment by fechanique** [comment]
merged!

2016-10-01 12:37 GMT+02:00 Felipe Echanique Torres <
felipe.echanique@gmail.com>:

**Comment by jorchg** [comment]
Thank you @fechanique !!!

**Comment by jtwiest** [comment]
@fechanique / @jorchg I updated the plugin by uninstalling / reinstalling through npm but still am not getting background notifications with iOS 10. In-app notifications work fine however.

Is there a step I'm missing here? Thanks.

**Comment by benlooi** [comment]
On IOS 10, there is a requirement to enable APN in XCode 8. It will only work on actual device, not simulator. Click on Capabilities tab, switch on Push Notifications. I think in your Apple Developer account, the Certs and Provisioning Profile for your app also need to enable Push notification. 
Also, enable Keychain too under Capabilities. 
You should see AppName.entitlements file appearing if set correctly.
I'm waiting for my App to be approved on App Store to give it a spin. Will update all if it works. My Push notifications comes from REST Api call from my server. 
*fingers crossed*

**Comment by jorchg** [comment]
@jtwiest Just try what @benlooi suggests. Also, in Xcode in capabilities I always enable the Background mode for push notifications, although it is supposed it is not needed. But with this update for me is working correctly.

**Comment by jtwiest** [comment]
@benlooi / @jorchg Got it working thanks a ton for the plugin / support.

Looks like when I updated xcode / iOS 10 my app's push notification settings (which were previously working) started showing an error. All I had to do was hit 'Fix Issue' and everything started working again.

**Comment by jorchg** [comment]
@jtwiest Glad of being helpful!! I think this should be closed now.

Cheers!

**Comment by sur** [comment]
Thanks so much @jorchg and @benlooi .
Was running into exact same problems when upgraded to Xcode8.

Just to summarise for others, this thread is really resolving two problems:
1) On Xcode8 (and iOS 10) not getting the Push notification at all when the app is in background
2) On Xcode8 (and iOS 10) getting the Push notification when app is in background, but tapping the notification is not invoking the  onNotification callback.

For 1) just go to Capabilities in Xcode and enable the Push Notifications setting.

For 2) remove the plugin completely and reinstall it from the repo and rebuild and it should work... here are commands (if anyone needs):
```
ionic plugin remove cordova-plugin-fcm
ionic plugin add https://github.com/fechanique/cordova-plugin-fcm.git
ionic build ios

```

**Comment by jpduckwo** [comment]
I'm having a problem where push is working, but when I fully close the app (double home click and swipe) then push notifications are not received in the background... is that normal behaviour?

**Comment by sur** [comment]
In short: that's not normal.

If the App is not in foreground (either in background or totally removed from the memory), there is really no relation with the Push to the App at this time. The Push Notification is between the device and the Push Server.

Once the Push Data is received on the App, the tapping of that Push Notification invokes the specific app (identified by the unique bundle identifier)... at this time if it's just in background, it will be brought to foreground, if it's not in memory, it will be instantiated.

So, if it's not working in all 3 conditions, there is some problem in the setup.

**Comment by jpduckwo** [comment]
Thanks, yep my setup was wrong. I disabled FirebaseAppDelegateProxyEnabled in my *-Info.plist and I think it broke push notifications.

**Comment by maxotov** [comment]
@benlooi, @jorchg, @sur i did all your steps, but not yet decide. I missed something? I get messages from my rest api via fcm in foreground well, but in background nothing occured. I use xcode 8.0 and iphone ios version 10.0.2. Also i added new type FirebaseAppDelegateProxyEnabled and set value NO in my *-Info.plist. But no results.

**Comment by jpduckwo** [comment]
@maxotov remove any reference to FirebaseAppDelegateProxyEnabled in your plist. Set priority high on your messages. Also I've seen it where background messages don't always get shown especially if you're sending the same test message over and over, or they get delayed and shown later.

**Comment by maxotov** [comment]
Thanks for quick answer. I solved. I missed notification section in my message, therefore push not received in background mode.
