### ISSUE TITLE
not receive notification

### ISSUE THREAD

**Issue by rafaelbsconsult** [fechanique/cordova-plugin-fcm#120]
i'm use tutorial but without successfully with virtual device IOS10.

code:

FCMPlugin.getToken(
             function(token) {
                 console.log(token);
             },
             function(err) {
                 console.log(err);
             }
         )

 FCMPlugin.onNotification(
            function(data) {
                if (data.wasTapped) {
                    //Notification was received on device tray and tapped by the user.
                    alert(JSON.stringify(data));
                } else {
                    //Notification was received in foreground. Maybe the user needs to be notified.
                    alert(JSON.stringify(data));
                }
            },
            function(msg) {
                console.log('onNotification callback successfully registered: ' + msg);
            },
            function(err) {
                console.log('Error registering onNotification callback: ' + err);
            }
        );

error:
onNotification callback successfully registered: null

following data to analysis:
cordova:6.3.1
ionic :2.1.0
ios 4.2.1

thank's.

**Comment by matheuscas** [comment]
Same to me. I have the FCM .plist in my root folder, also I sent the .p12 to development mode and I always get a null token.
