### ISSUE TITLE
IOS Dont show any notification

### ISSUE THREAD

**Issue by MateusAndrade** [fechanique/cordova-plugin-fcm#126]
Hello, I managed to set the normalmenten project, add Google-Services, etc., and record the phone returning an id on the alert, however when I try to send a push message from the firebase console on my Android I get it often, but the ios do not. Testing sending with the application open, it ends up happening the same but with the following log:

`2016-10-04 11:06:08.273 Terminal Profissional[257:] <FIRAnalytics/ERROR> Encounter network error. Error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://play.googleapis.com/log, _kCFStreamErrorCodeKey=-2103, NSErrorFailingURLKey=https://play.googleapis.com/log, NSLocalizedDescription=The request timed out., _kCFStreamErrorDomainKey=4}`

What can be the possible mistake, that iam doing?

**Comment by dannywillems** [comment]
@MateusAndrade Did you find a solution?

**Comment by MateusAndrade** [comment]
Yes, i uploaded both development and distribution certificates that i got from Apple Member Center, to the "ios section" of firebase.

**Comment by gongyujun** [comment]
@MateusAndrade Hi, could you describe the solution in details? Thanks!

**Comment by MateusAndrade** [comment]
@gongyujun  yep, it has been a long time since i've managed this, but the solution that i found was upload the Certs that you get from Apple Member Center to the Firebase Console. At the moment i cant tell you which are the certs because im having some problems with my account on Apple Member Center.

Try searching for: Firebase uploading Apple Certs, or something like this.
