### ISSUE TITLE
FCM token is now null on Android emuator

### ISSUE THREAD

**Issue by camden-kid** [fechanique/cordova-plugin-fcm#129]
I noticed that the FCM token is now always null when my app is run on an Android emulator whereas up until recently a valid token was returned. A valid token is still returned when the app runs on an actual device though.

Could this be somehow related to the Android Support Library now being obsolete? I don't know much about how this plugin works so I'm just hazarding a guess.

![image](https://cloud.githubusercontent.com/assets/890197/19180973/c8688410-8c61-11e6-9d01-2bff2f696914.png)

**Comment by corentinbaur** [comment]
Token generation is only working on Google APIs system images.
You can read this issue, it can help you .

https://github.com/phonegap/phonegap-plugin-push/issues/643#issuecomment-188257964

**Comment by camden-kid** [comment]
@corentinbaur Thanks. I remade my AVD with Google APIs intel Atom (x86) and it worked.
