### ISSUE TITLE
How should I send notification to specific device?

### ISSUE THREAD

**Issue by RezaRahmati** [fechanique/cordova-plugin-fcm#13]
How should I send notification to specific device

 "to":"/topics/topicExample", //Topic or single device

**Comment by fechanique** [comment]
You can use setTopic function in order to identify a device, or wait for the next version which will have the getToken function implemented.

**Comment by RezaRahmati** [comment]
Thanks for fast response.
Sorry, I cannot find "setTopic" in docs or in FcmPlugin.js to see how should I use that.
Another question, Is getToken will be released soon?

**Comment by fechanique** [comment]
In the readme you can find:
`FCMPlugin.subscribeToTopic('topicExample', successCallback, errorCallback);`

Tomorrow I will publish a release with getToken functionality

**Comment by RezaRahmati** [comment]
Great, I am looking forward to it. :+1:
