### ISSUE TITLE
Any tutorial for iOS? 

### ISSUE THREAD

**Issue by Fayozjon** [fechanique/cordova-plugin-fcm#134]
Hi there!
Please share some directions how to add ionic IOS version FCM?
There says something like cocoa pod Firebase and so on... 
If there will be some kind of step-by-step tutorial i will appreciate it.
Thank you!

**Comment by rossi256** [comment]
Would also be very interested in more details about iOS.
For your info - i managed to make it work a little - i see test-notifications in foreground and background. however i have huge amounts of warnings in Xcode console.
You don't need to do the cocoa pod things mentioned on firebase and there are some sort of tutorials for the certificate stuff...step by step information for how to start with a new app - just google...

i did it several times and what worked for me enough to get notifications is:
1. open keychain on your mac and request code signing certificate (menu keychain access - certificate assistant - request certificate. enter email and save to disk)
2. go to iOS membercenter to your app, enable push notifications and create certificate there with the certificate request - save cert, double-click to add to your keychain
3. go to the certificate and right click, export as p12 file.
4. upload that p12 cert to firebase in console - cloud messaging

the googleservice-info.plist goes in your resources directory - drag it to Xcode and link or copy it to add to the project.

as said its not working

**Comment by Fayozjon** [comment]
Thank you very much!

**Comment by tordnilsen** [comment]
Is this working if you use Ionic Package also?

**Comment by mailtoamirjohn** [comment]
I referred [this youtube channel](https://www.youtube.com/watch?v=qZLmt5NK8Gs)
