### ISSUE TITLE
data.wasTapped retrun string 

### ISSUE THREAD

**Issue by glasset** [fechanique/cordova-plugin-fcm#14]
I think is better to return a bool for `data.wasTapped` instead of a string.
we can't check like this `if (data.wasTapped)` or `if (!data.wasTapped)`.

btw thank you for the quick release :)

**Comment by fechanique** [comment]
Is not so easy to implement a functionality on Android and iOS at the same time, so I went by the quick path to solve this. When I have more time I'll check this,

**Comment by fechanique** [comment]
fixed, now returns a boolean!
