### ISSUE TITLE
AppDelegate+FCMPLugin for IOS10

### ISSUE THREAD

**Issue by benlooi** [fechanique/cordova-plugin-fcm#145]
Hi all, just sharing how I got rid of the old deprecated warnings with this new updated one. 
1. Add new XCode framework UserNotifications first by going to Build Phases and add new binary.
2. add thisline to to the top area of AppDelegate+FCMPlugin.m where all the #import lines are, after Foundation:
#import <UserNotifications/UserNotifications.h>

3. Change your AppDelegate+FCMPlugin file where the old code is to this:

if (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_9_x_Max) {
        UIUserNotificationType allNotificationTypes =
        (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);
        UIUserNotificationSettings *settings =
        [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];
        [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
    } else {
        // iOS 10 or later
#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
        UNAuthorizationOptions authOptions =
        UNAuthorizationOptionAlert
        | UNAuthorizationOptionSound
        | UNAuthorizationOptionBadge;
        [[UNUserNotificationCenter currentNotificationCenter]
         requestAuthorizationWithOptions:authOptions
         completionHandler:^(BOOL granted, NSError * _Nullable error) {
         }
         ];
        
        // For iOS 10 display notification (sent via APNS)
        [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
        // For iOS 10 data message (sent via FCM)
        [[FIRMessaging messaging] setRemoteMessageDelegate:self];
#endif
    }
    
    [[UIApplication sharedApplication] registerForRemoteNotifications];

Seems to work.

**Comment by bmwertman** [comment]
Hi, I'm not sure I understand how to use your fix. Here are screenshots for before and after. Can you help? Thanks

Before
![screen shot 2016-10-20 at 10 34 22 am](https://cloud.githubusercontent.com/assets/2573903/19564316/25d28d7c-96b1-11e6-8762-f1f961b0c8d3.png)

After
![screen shot 2016-10-20 at 10 33 33 am](https://cloud.githubusercontent.com/assets/2573903/19564284/083531ca-96b1-11e6-96f3-84a647dcb075.png)
