### ISSUE TITLE
Push not working for iOS production but works for development

### ISSUE THREAD

**Issue by jpduckwo** [fechanique/cordova-plugin-fcm#150]
Hi, I have both Dev and Prod APN certificates generated and applied in the APP-ID and uploaded to firebase. 

When I generate a token and do a push locally with development, push notifications are working fine. However when I upload to TestFlight and Production none of the push notifications are coming through to the apps (although Firebase says success).

I've doubled check all the certificate settings and Xcode project settings, entitlements and capabilities and they all seem ok. I was wondering if this statement might be the issue: from:https://firebase.google.com/docs/cloud-messaging/ios/certs#configure_an_app_id_for_push_notifications

![image](https://cloud.githubusercontent.com/assets/13150911/19550106/aa17da50-96f3-11e6-8fc5-19cf1c5679c6.png)

I think this means that when the token is generated it will generate one either for Production or Development based on the provisioning profile, but if you're calling setAPNSToken you need to set it explicitly. I was wondering if the plugin might be affected by this?

I've tested with an iPhone 6 with iOS10 and and iPad with iOS9. Has anyone got success with push notifications in production with iOS? Or perhaps any other hint I might have missed?

**Comment by jpduckwo** [comment]
Ok I think this was because I had set FirebaseAppDelegateProxyEnabled:NO in my plist file. This broke push notifications to IOS from firebase.

**Comment by thecombo** [comment]
That does not appear to me!!
where is that option in Xcode project???
