### ISSUE TITLE
Notification Icon too small on Android > 5.0

### ISSUE THREAD

**Issue by OshyBlock** [fechanique/cordova-plugin-fcm#157]
Hi!, I have the plugin working and everything, I get the callback when the notification gets pressed and everything works fine, except for one thing on Android > 5.0 the icon on the notification bar looks OK, but when I drag the notification bar down to see all the notifications the icon of my notification is really small
![screenshot_2016-10-25-22-01-15](https://cloud.githubusercontent.com/assets/10590587/19709696/e5255ec4-9afe-11e6-801e-db51f2d419b4.png)

I generated the icons with this [tool](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=0&source.space.pad=0&name=fcm_push_icon), and placed them on "AppName\platforms\android\res\drawable-xxxxx" respectively
I also have the option "icon" : "fcm_push_icon" on my payload so... I don't know what I'm doing wrong here...
Any ideas?

Also... unrelated to the first question... is there a way to change the color of the circle in the notification icon?

**Comment by ivankennethwang** [comment]
Is there no solution for this?

**Comment by shakegioh** [comment]
@OshyBlock did you solve the "really small" problem?
Also, thanks for the color tip
