### ISSUE TITLE
Build FAILED

### ISSUE THREAD

**Issue by DanielMutu** [fechanique/cordova-plugin-fcm#158]
Hi, when i build i have this error:

---

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':processDebugGoogleServices'.
  
  > No matching client found for package name 'com.example.AAA'
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  ---

**Comment by kamilo81** [comment]
+1

**Comment by erica07312002** [comment]
The solution is, you have to set config <widget id="</strong> in <strong>config.xml</strong> to your <strong>"package_name" from google-service.json you configured in firebird configuration.
References: http://ionic168.rssing.com/chan-53730660/all_p469.html
