### ISSUE TITLE
Request for step-by-step manual with screenshots

### ISSUE THREAD

**Issue by jamesaung** [fechanique/cordova-plugin-fcm#17]
Hello,

Can I request you the step-by-step guide to develop FCM feature in a cordova project?
There is no guide on Firebase website (how to use FCM with cordova project)

Thanks,
James

**Comment by fechanique** [comment]
You only need to generate your configurations files for both iOS and Android and install the plugin.

https://firebase.google.com/docs/cloud-messaging/ios/certs#configure_an_app_id_for_push_notifications

**Comment by Krisa** [comment]
I agree it might be misleading... 

Screenshots might not be required but it should be at least highlighted what to do. For instance, I started yesterday to follow the instructions provided and modified the gradle file, the manifest, till I realised that what I was doing was redundant with this plugin... The only thing to do for Android is indeed to generate the .json file and copy paste it in platforms/android folder... and this works. Oh and the key to be used to send notifications, is not the key found in the .JSON file you've generated but in your app here: https://console.firebase.google.com/project/YOURPROJECT/settings/cloudmessaging.

This plugin makes things really simple, but there is a bare minimum to do and the Readme should be a bit more clear on that.

**Comment by RezaRahmati** [comment]
@Krisa  What do you mean by "Oh and the key to be used to send notifications, is not the key found in the .JSON file you've generated but in your app here"? would you elaborate it more?

**Comment by Krisa** [comment]
@RezaRahmati the key in the .JSON is used by the client itself. The key used for the server is different, and can be found directly in the firebase console.

**Comment by RezaRahmati** [comment]
@Krisa  thanks, my file content is like that, which key do you mean? and do we need to do any modification in the file?

```
{
  "project_info": {
    "project_number": "111111",
    "firebase_url": "https://xxxxx-42189.firebaseio.com",
    "project_id": "xxxxx-42189",
    "storage_bucket": "jarchee-xxxxx.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:22334445567:android:xxxxxyyyyyzzzzz",
        "android_client_info": {
          "package_name": "com.xxxx.xxxx"
        }
      },
      "oauth_client": [
        {
          "client_id": "22334422-35vu2evvrctrttrskkqps18unjev2.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "AIzaSyC7n9i8f1j-ddrrdsdsxxxeee_78"
        }
      ],
      "services": {
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 2
        }
      }
    }
  ],
  "configuration_version": "1"
}
```

**Comment by Krisa** [comment]
Yep, so again, the key to send notification is **not** to be found in your json file, but in the firebase console. To find it, log in your project, click on the Cog icon to go in the project settings, then Cloud Messaging and you will see the Server Key there.

**Comment by RezaRahmati** [comment]
@Krisa Now I see :)
