### ISSUE TITLE
When editing plugin files, changes seems not beeing changed in application. 

### ISSUE THREAD

**Issue by ramon8** [fechanique/cordova-plugin-fcm#185]
Hi, 
when i try to edit the conf files from android/src, when i compile the application those files seems not beeing changed, and i dont know  what to do, some suggestion?

Thanks.

Ramon Fernandez.

**Comment by codewise-nicolas** [comment]
Are you editing the files inside platform/..plugins, or under /plugins
In my experience when editing /plugins files, changes are not pushed to the platform/...plugins folder on build.

In order for changes to be pushed to the platform folder you need to either remove/re-add the plugin, OR remove/re-add the platform.

**Comment by ramon8** [comment]
Oh thanks @codewise-nicolas! 
I'm new on this and i dont know exactly how works, so thanks you again.

SOLVED - Basically what i did was to upload the plugin from local instead of being installed from git, and then, in any time that I want to edit configuration files just reinstalling the plugin works.
