### ISSUE TITLE
How to implement with Ionic2/typescript

### ISSUE THREAD

**Issue by majodi** [fechanique/cordova-plugin-fcm#19]
Any thoughts on this:

http://stackoverflow.com/questions/38127145/how-to-use-cordova-plugin-with-ionic-2-typescript

Thnx

**Comment by majodi** [comment]
Never mind, issue solved.

**Comment by timmyrosen** [comment]
Hi @majodi 

Do you mind sharing your solution to this?

**Comment by majodi** [comment]
It's on stackoverflow, just follow the link above
