### ISSUE TITLE
Cannot find name 'FCMPlugin'

### ISSUE THREAD

**Issue by synga** [fechanique/cordova-plugin-fcm#191]
Hi everyone. I'm trying to use this plugin with Ionic 2 and i've followed some simple tutorials (like this: [Ionic 2 FCM Notifications](http://simonwillshire.com/blog/Ionic-2-FCM-Notifications/)) about how to use it.
I have this piece of code on my 'platform.ready()':
`if (typeof(FCMPlugin) !== "undefined") {
                    FCMPlugin.getToken(function (t) {
                        console.log("Use this token for sending device specific messages\nToken: " + t);
                    }, function (e) {
                        console.log("Uh-Oh!\n" + e);
                    });
                };`

But it throws me a 'Cannot find name FCMPlugin'. I'm not importing anything and to be fair i've even understod how to use the plugin 'cause i usually import it from 'ionic-native', so what is wrong?

**Comment by synga** [comment]
Nevermind just got it. Need to add a 'declare var FCMPlugin: any' within my imports in the page i want to use the plugin and ser a <script> to the plugin .js file in my home.html

**Comment by brobilal** [comment]
Hi @synga : you said: Need to add a 'declare var FCMPlugin: any' within my imports in the page i want to use the plugin and ser a <script> to the plugin .js file in my home.html. 

How exactly did you do this??

**Comment by brobilal** [comment]
hi, think post helped me a lot to understand how to proceed without the declarations.d.ts file: https://github.com/fechanique/cordova-plugin-fcm/issues/154#issuecomment-388540997
