### ISSUE TITLE
wasTapped only works when app is closed&destroyed

### ISSUE THREAD

**Issue by synga** [fechanique/cordova-plugin-fcm#194]
I've seen a lot of people writing issues complaining about this and now i've faced the same problem.
So, apparently, when you exit the app via back button and receive a push, clicking the push on tray will not do anything, it simply gives a blank screen.
But when you leave the app and kill it (like via android "recent apps" button) you're able to handle the wasTapped and the app opens normally.

So is there a solution for this already or is this a future update?
I've followed exactly how the plugin read.me instructs to, and i know there's a lot of ppl leaving this plugin and using phonegap-push or cordova-firebase

**Comment by jonasneustupny** [comment]
I hope that helps: https://github.com/fechanique/cordova-plugin-fcm/issues/192 (see my update below)
