### ISSUE TITLE
Receive callback with data ?

### ISSUE THREAD

**Issue by wilsonpinto360** [fechanique/cordova-plugin-fcm#20]
What Is the correct way to get the data/message from the notification to the app via a callback?

There is 2 different scenarios: 
-  Background/ App off
   Show Notification in toolbar
   When notification is clicked, receive callback with data (**not working, android 6.0 cordova 6.2**).

- Foreground (working):
  Receive callback with data.

onNotification listener is never trigger when first scenario occurs.

**Comment by wilsonpinto360** [comment]
Ok i found the problem, 
I was using firebase console for testing...You need make sure that payload will contain this values: 
>    
    "click_action":"FCM_PLUGIN_ACTIVITY",  //Must be present for Android 
> 

Maybe it's better idea to make sure that this under android requirements.

**Comment by fechanique** [comment]
It's explained in the Usage Section
