### ISSUE TITLE
2.0.0 doesn't trigger onTokenRefresh() callback

### ISSUE THREAD

**Issue by gianpaj** [fechanique/cordova-plugin-fcm#204]
I have this in my app but it's never executed:
```
FCMPlugin.onTokenRefresh(function(token){
    alert( token )
  });
```
I believe is because the `exec()` is longer here:
https://github.com/fechanique/cordova-plugin-fcm/commit/06dc209e39bf61498fa154dc97b588f43f2e1406#diff-edb15773e0711de1c49bd7a6d3eed3dbR29

(i'm not sure if the `onTokenRefreshReceived` is triggered in a different way)

**Comment by fechanique** [comment]
No, it should works

**Comment by etherny** [comment]
Same issue here.
here my android studio log : 

FCMPlugin

01-14 17:10:57.622 27083-27083/#projectPackage# D/FCMPlugin: ==> FCMPlugin initialize
01-14 17:11:07.275 27083-27247/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: ready
01-14 17:11:07.315 27083-27083/#projectPackage# D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js: Line 5 : FCMPlugin.js: is created
01-14 17:11:07.315 27083-27083/#projectPackage# I/chromium: [INFO:CONSOLE(5)] "FCMPlugin.js: is created", source: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js (5)
01-14 17:11:09.658 27083-27083/#projectPackage# D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js: Line 39 : FCMPlugin Ready OK
01-14 17:11:09.659 27083-27083/#projectPackage# I/chromium: [INFO:CONSOLE(39)] "FCMPlugin Ready OK", source: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js (39)
01-14 17:11:10.735 27083-27247/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: registerNotification
01-14 17:11:10.758 27083-27247/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: subscribeToTopic
01-14 17:11:10.774 27083-27247/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: subscribeToTopic
01-14 17:11:10.778 27083-27247/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: subscribeToTopic

Firebase 

01-14 17:12:04.383 27840-27840/#projectPackage# D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
01-14 17:12:04.424 27840-27840/#projectPackage# D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
01-14 17:12:04.572 27840-27840/#projectPackage# I/FA: To enable faster debug mode event logging run:
                                                          adb shell setprop debug.firebase.analytics.app #projectPackage#
01-14 17:12:04.578 27840-27840/#projectPackage# I/FirebaseInitProvider: FirebaseApp initialization successful
01-14 17:12:06.243 27840-27915/#projectPackage# D/FirebaseInstanceId: topic sync succeeded
01-14 17:12:13.960 27840-28018/#projectPackage# D/FirebaseInstanceId: topic sync succeeded

With the last 2.0.0 version. Working with the old version.

01-14 17:29:08.707 11888-11888/#projectPackage# D/FCMPlugin: ==> FCMPlugin initialize
01-14 17:29:13.370 11888-12016/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: ready
01-14 17:29:13.375 11888-11888/#projectPackage# D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js: Line 5 : FCMPlugin.js: is created
01-14 17:29:13.375 11888-11888/#projectPackage# I/chromium: [INFO:CONSOLE(5)] "FCMPlugin.js: is created", source: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js (5)
01-14 17:29:13.390 11888-11888/#projectPackage# D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js: Line 35 : FCMPlugin Ready OK
01-14 17:29:13.390 11888-11888/#projectPackage# I/chromium: [INFO:CONSOLE(35)] "FCMPlugin Ready OK", source: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js (35)
01-14 17:29:13.668 11888-12016/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: registerNotification
01-14 17:29:13.673 11888-12016/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: subscribeToTopic
01-14 17:29:13.678 11888-12016/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: subscribeToTopic
01-14 17:29:13.684 11888-12016/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: subscribeToTopic
01-14 17:29:13.731 11888-12016/#projectPackage# D/FCMPlugin: ==> FCMPlugin execute: getToken
01-14 17:29:14.267 11888-11888/#projectPackage# D/FCMPlugin: 	Token: {"token":"dPYUoGVMVkY:APA91bHAqQqakITyuFNoITwXuQOhtCTUsLbZfJqy###########NZbL2P7WHG8RfFQSQ-ywi_4PfrFrAwL-","appVersion":"10000","timestamp":1484368260976}

**Comment by tessdar** [comment]
I also have the same issue about "FCMPlugin.onTokenRefresh()".
Thank you for your help in advance.

**Comment by fechanique** [comment]
That funtion is only called when a new token is generated, try uninstalling
the application and installing it again, also that function is usually
called when the app is loaded (when the device connects to Firebase), so
onDeviceReady is the best place to put that function and save the token

El 15/1/2017 11:05, "tessdar" <notifications@github.com> escribió:

I also have the same issue about "FCMPlugin.onTokenRefresh()".
Thank you for your help in advance.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fechanique/cordova-plugin-fcm/issues/204#issuecomment-272685462>,
or mute the thread

**Comment by tessdar** [comment]
It works. Thank you so much.

**Comment by gianpaj** [comment]
I'm not using this plugin anymore so I'm closing this issue. Cheers

**Comment by elewin** [comment]
I have onTokenRefresh in device ready, however it is never seeing a new token. getToken does work however. Other people seem to be having this problem in other issues as well. Any ideas?
