### ISSUE TITLE
How to open certain page/state after clicking notification

### ISSUE THREAD

**Issue by ilman** [fechanique/cordova-plugin-fcm#215]
Hi, 

I am using FCMPlugin.onNotification but its only run when the notification arrives, not when user click the notification.

How do I detect event when user click the notification and then redirect it to certain page/state in my app?

**Comment by kapilrc** [comment]
```
// Push notifications MUST be registered as early as possible
$(document).on("deviceready", function() {
  // Push notifications handling
  FCMPlugin.onNotification(
      function(data) {
        if(data.wasTapped) {
          console.log("Push Notification tapped", data);
          window.route("/to-notification");
        }else {
         // this will be the state when app is already opened.
          console.log("Push Notification", data);
          Notification.info("You have new notifications");
        }
      },
      function(msg) {
        console.log('onNotification callback successfully registered: ' + msg);
      },
      function(err) {
        console.log('Error registering onNotification callback: ' + err);
      }
  );
}); 
```

**Comment by ilman** [comment]
@kapilrc thanks for your reply!

I was using the same code, but the onNotification event never fired if the app is not opened/in foreground. 

And when user click notification its never fired too.

Any advice for that?

**Comment by bitroot-engineering** [comment]
I don't know if this is the reason or not, but make sure your messages are sent with the `"click_action":"FCM_PLUGIN_ACTIVITY"` in the notification block. If you send a message without that, it will open the application but won't trigger the method in the plugin. I had the same problem last night.

Here's the sample from the readme page:

```
{
"notification":{
    "title":"Notification title",
    "body":"Notification body",
    "sound":"default",
    "click_action":"FCM_PLUGIN_ACTIVITY",
    "icon":"fcm_push_icon"
  },
  "data":{
    "param1":"value1",
    "param2":"value2"
  },
    "to":"/topics/topicExample",
    "priority":"high",
    "restricted_package_name":""
}
```

**Comment by kapilrc** [comment]
What should be the relative path for fcm_push_icon.png

In Android Lollipop, I have added this image in res folder, still am getting white image in the notification tray!

**Comment by ilman** [comment]
@bitroot-engineering wow, thanks a ton for the info!

I was testing from firebase console before, which doesnt have "click_action":"FCM_PLUGIN_ACTIVITY" property. And now using the test server on appspot, the click event is working now. Thanks again!

**Comment by kapilSoni101** [comment]
@bitroot-engineering - ur solution is working perfectly  but for iOS in background then click notification but onNotification not fire in background as well foreground.can you tell me sir why?
