### ISSUE TITLE
Invalid data 

### ISSUE THREAD

**Issue by rogergajraj** [fechanique/cordova-plugin-fcm#217]
I added the generated google-services.json file and then tried to install plugin:

![screen shot 2017-01-20 at 1 01 59 am](https://cloud.githubusercontent.com/assets/13014884/22136652/2a03037a-deac-11e6-8c7f-605104de56a8.png)

**Comment by rogergajraj** [comment]
in the meanwhile, I use v1.1.5
`cordova plugin add https://github.com/fechanique/cordova-plugin-fcm#503f2fbb8d9fd9446212d4300f985c1df44389ec`

**Comment by jackread** [comment]
I solved this by removing the <info> tags in the plugin.xml

**Comment by rogergajraj** [comment]
The issue was that the first google-services.json file, given by google, did not have a key inserted. You have to go and redownload it again or manually insert it.

`"api_key": [
        {
          "current_key": "AIzaS... .. . . . . . . . . . .JsF"
        }
      ],`
