### ISSUE TITLE
onNotification not called when tapping notification

### ISSUE THREAD

**Issue by victorleduc** [fechanique/cordova-plugin-fcm#225]
Hi,

The onNotification function is not called when the app in is the background and I tapp on the notification.

Strangly, it works with your tester : cordova-plugin-fcm.appspot.com

But I don't understand what I did wrong.. Here is my json : 

```
{
	"to": "fwOlZHdJIDA:APA91bEAX6PzKoeiYGV1IZ_QI2z4bAJFmFhcKQ7uQzQWA1SmSUNyjW0oXTt7yAW0WGzq8njhZ5n_-LrX_fs3qMIyxPiwgxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"data": {
		"some data": 42
	},
	"notification": {
		"body":"Body",
		"title":"Title"
	}
}
```

Can you tell me what does your json look like with your tester (cordova-plugin-fcm.appspot.com) ?

Thanks in advance :)

**Comment by victorleduc** [comment]
Sorry I found my mistake, I forgot "click_action": "FCM_PLUGIN_ACTIVITY"

**Comment by kapilrc** [comment]
:+1: 
@victorleduc: this works for android. 
But tap event is not captured in iOS, not even with your tester: cordova-plugin-fcm.appspot.com

Any help?

Thanks,
Kapil

**Comment by ragcsalo** [comment]
Tap event is captured on iOS only when the app is in the background, but not when closed... any solution for this?
