### ISSUE TITLE
How to get started with this plugin with ionic?

### ISSUE THREAD

**Issue by 00Alaa00** [fechanique/cordova-plugin-fcm#233]
hello,

how to get started using this plugin with ionic framework? 
i did the following steps but it doesn't work:

1. create new ionic project: ionic start app blank
2. add ios and android platforms: ionic platform add ios/android
3. get app id from confog.xml: widget id="com.ionicframework.app1251173" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0"
4. went to firebase and created config files using app id above and put them in app root directory and inside platforms/android and platforms/ios
5. installed this plugin 
6. i build the app with ionic build ios/android
7. i run emulator with ionic run ios
8. went to firebase console and send message and nothing show up in the emulator 

can someone please explain how to get this plugin to work

**Comment by nutella** [comment]
This plugin works only on real device, not on emulator...

**Comment by 00Alaa00** [comment]
@nutella Thanks so much! it did work on my phone :) also it worked on the android emulator :)

**Comment by Umar-Abbas** [comment]
@00Alaa00 

Hi!
Could you please tell how it works for you? i am totally stuck at that point .

Thanks

**Comment by 00Alaa00** [comment]
Hi @Umar-Abbas i didn't do anything other than the steps above, at first it didn't work, but it worked the next day i have no idea why, i think maybe you need to wait until firebase register/recognize your device for push notifications.

**Comment by nutella** [comment]
Yes, normally you need to wait some times...
