### ISSUE TITLE
testing service

### ISSUE THREAD

**Issue by nutella** [fechanique/cordova-plugin-fcm#235]
I've tried to send a test message from https://cordova-plugin-fcm.appspot.com and I got the error: invalid api key, but if I try from firebase console, the message will arrive correctly. What's wrong?

**Comment by fureszk** [comment]
use the server key from here: https://console.firebase.google.com/project/YOUR_PROJECT/settings/cloudmessaging

**Comment by nutella** [comment]
Yes, but my server key begin with AIzaSyB.....

**Comment by fureszk** [comment]
are you sure?
http://puu.sh/tQUoV/052809368a.png

**Comment by nutella** [comment]
Ok, there is a strange thing. My previous (server) key begin with AIzaSyCy*** but firebase has upgraded my server key to the new one: AAAAJqi*****. The key that begin with AlzaSyB*** is the API key. However is only for testing, because I put sending script on my server when all works, so thanks and sorry ;)

ps. using old server key, works well without problems

**Comment by frjufvjn** [comment]
https://cordova-plugin-fcm.appspot.com is not working...
I use official firebase console.
https://console.firebase.google.com/project/[your-project-name]/notification
