### ISSUE TITLE
ios does not receive notifications

### ISSUE THREAD

**Issue by yoprogramo** [fechanique/cordova-plugin-fcm#236]
I have tested the Android version and it works correctly, receiving messages and so on. On iOS, my app receive the token correctly, but when I try to send messages to this token nothing happend (even from firebase console)... What can I debug/review taking into account that the Android version does receive the messages??

**Comment by MartijnVooges** [comment]
"Apparently there is an error in the Firebase documentation. When you exporting the APN certificate for production from your keychain to the .p12 file you have to select the actual certificate, not the private key."

http://stackoverflow.com/a/41696213/2519416

**Comment by yoprogramo** [comment]
I exported the full certificates... The full log of initialization is:

> 2017-01-30 11:37:00.739 NoMorePass[4743:1440514] Apache Cordova native platform version 4.3.1 is starting.
> 2017-01-30 11:37:00.743 NoMorePass[4743:1440514] Multi-tasking -> Device: YES, App: YES
> 2017-01-30 11:37:01.335 NoMorePass[4743:1440514] Using UIWebView
> 2017-01-30 11:37:01.342 NoMorePass[4743:1440514] [CDVTimer][handleopenurl] 0.344992ms
> 2017-01-30 11:37:01.362 NoMorePass[4743:1440514] [CDVTimer][intentandnavigationfilter] 19.535005ms
> 2017-01-30 11:37:01.364 NoMorePass[4743:1440514] [CDVTimer][gesturehandler] 0.343025ms
> 2017-01-30 11:37:01.420 NoMorePass[4743:1440514] [CDVTimer][localstorage] 55.577993ms
> 2017-01-30 11:37:01.421 NoMorePass[4743:1440514] [CDVTimer][TotalPluginStartup] 79.334021ms
> 2017-01-30 11:37:01.497 NoMorePass[4743:1440514] DidFinishLaunchingWithOptions
> 2017-01-30 11:37:01.628 NoMorePass[4743] <Debug> [Firebase/Core][I-COR000001] Configuring the default app.
> 2017-01-30 11:37:01.629: <FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
> 2017-01-30 11:37:01.640: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
> 2017-01-30 11:37:01.655: <FIRMessaging/INFO> FIRMessaging library version 1.2.0
> 2017-01-30 11:37:01.673: <FIRMessaging/WARNING> FIRMessaging AppDelegate proxy enabled, will swizzle app delegate remote notification receiver handlers. Add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
> 2017-01-30 11:37:01.685 NoMorePass[4743:1440514] app become active
> 2017-01-30 11:37:01.754 NoMorePass[4743:] <FIRAnalytics/INFO> Firebase Analytics v.3403000 started
> 2017-01-30 11:37:01.756 NoMorePass[4743:] <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
> 2017-01-30 11:37:01.896 NoMorePass[4743:] <FIRAnalytics/INFO> Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
> 2017-01-30 11:37:03.261: <FIRInstanceID/WARNING> APNS Environment in profile: development
> 2017-01-30 11:37:03.410 NoMorePass[4743:1440514] Resetting plugins due to page load.
> 2017-01-30 11:37:03.478 NoMorePass[4743:1440514] Connected to FCM.
> 2017-01-30 11:37:03.506 NoMorePass[4743] <Debug> [Firebase/Core][I-COR000019] Clearcut post completed.
> 2017-01-30 11:37:04.702 NoMorePass[4743:1440514] Finished load of: file:///var/containers/Bundle/Application/9027C6C0-5503-4B36-994E-809B118E2913/NoMorePass.app/www/index.html#!home
> 2017-01-30 11:37:05.020 NoMorePass[4743:1440514] Cordova view ready
> 2017-01-30 11:37:05.112 NoMorePass[4743:1440514] view registered for notifications
> 2017-01-30 11:37:07.197 NoMorePass[4743:] <FIRAnalytics/WARNING> The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
> 2017-01-30 11:37:08.314 NoMorePass[4743:] <FIRAnalytics/INFO> Firebase Analytics enabled

I presume the problem is in the line:

> 2017-01-30 11:37:01.640: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"

**Comment by yoprogramo** [comment]
After changing capabilities and adding FirebaseAppDelegateProxyEnabled to false something comes to the app when I send a message, but now I get:

> <FIRMessaging/WARNING> Error none of the remote notification callbacks implemented by UIApplicationDelegate

What's next?

**Comment by MartijnVooges** [comment]
Sorry, can't help you with that. That topic/answer was a 100% fit solution in my case.

**Comment by yoprogramo** [comment]
Just to close this issue.. There are some other test/debug/check to try to detect/fix the problem?

Regards

**Comment by shaharyar123** [comment]
@yoprogramo  i am facing the same issue 
`<FIRMessaging/WARNING> Error none of the remote notification callbacks implemented by UIApplicationDelegate`

did you solve it ?

**Comment by yoprogramo** [comment]
@shaharyar123 , no, I'm in a dead end in this case... Android works fine but iOS doesn't receive the messages. If you find finally some solution, please share with us!!

**Comment by shaharyar123** [comment]
@yoprogramo  i have removed 

> `FirebaseAppDelegateProxyEnabled`

from the info.plist and started receiving notification on  iphone 5, 6 but not on 4s model. I dont know why!
what ios version and iphone you are using ?

**Comment by yoprogramo** [comment]
I test with iphone 5 with latest ios and ipad mini with ios 9
When I removed this entry from plist simply I received nothing.

**Comment by shaharyar123** [comment]
@yoprogramo  try with upgrading to ios version 10. it will work. (hope so)

**Comment by yoprogramo** [comment]
@shaharyar123 : confirmed. iOS10 works, so, it is a problem just with iOS<10 as pointed in #247 , so I close this issue.
