### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by icernn03** [fechanique/cordova-plugin-fcm#24]
Build fails after I have added the plugin. I am using google-services 9.2.0 Build fails asking to update google-services but succesfully builds if I remove the plugin
noticed plugin uses 9.0.0 and gradle 1.1.0. Need guidance how to setup the plugin in my project
I cannot downgrade google-services since firebase require to use latest sdks

**Comment by epaezrubio** [comment]
+1

**Comment by florinmtsc** [comment]
+1

**Comment by fechanique** [comment]
I have updated the plugin to 9.2.0 fcm version
