### ISSUE TITLE
Push notifications to single device

### ISSUE THREAD

**Issue by eddie-lu** [fechanique/cordova-plugin-fcm#243]
I am trying to send notifications to a single device. I'm using the Ionic (v1) platform. getToken() is called and I get a token but whenever I try to send a notification to this token from the Firebase console, I get a failed status. I can send notifications to all devices and to a topic. I can also subscribe to a topic successfully. 
Is there anything I'm missing?
The functions for getToken() is in the ready(() function.

**Comment by ole1986** [comment]
the result of getToken() should look similar to this:

`cxYB****dYc:APA91bHcY******-pf4Fw-u-Etxos6exwGKqm******XBXJ-enT3FF****ghFHDK**6kinAJ-XLAdvn****jBGIh`

make sure you have stored the push token properly.
You can also get the token using `adb logcat` - FCMPlugin will console.log it for you.

**Comment by eddie-lu** [comment]
Thanks. 
I think I was storing the token wrong. My table was truncating the token without giving me a warning. Managed to push it.
