### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by LeoGuanco** [fechanique/cordova-plugin-fcm#250]
Hello, i have installed the google-maps plugin and my problem is that when installing the FCM plugin gives me this error:

    >**Execution failed for task ':processDebugGoogleServices'.
    Please fix the version conflict either by updating the version of the google-s
    ervices plugin (information about the latest version is available at https://bin
    tray.com/android/android-tools/com.google.gms.google-services/) or updating the
    version of com.google.android.gms to 9.0.0.**

I changed the google-play-services version to 9.0.0 in project.properties but now it gives me this error:

    >**import com.google.android.gms.maps.model.MapStyleOptions;
    ^
    symbol: class MapStyleOptions
    location: package com.google.android.gms.maps.model**

Anyone have the solution?

**Comment by vabiro** [comment]
I'm getting the same error. Whether I try to compile in Android Studio or PhoneGap CLI, the same thing.

Here are the plug-ins that are installed:

> $ phonegap plugin list
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-fcm 2.1.1 "FCMPlugin"
cordova-plugin-googleplayservices 19.0.3 "Google Play Services for Android"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
phonegap-plugin-push 1.8.4 "PushPlugin"

>

**Comment by LeoGuanco** [comment]
@vabiro watch this https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1302#issuecomment-279612971

**Comment by vabiro** [comment]
@LeoGuanco Thanks. It looks like this isn't the only plug-in that's having a problem. I'm not sure if closing the other issue was going to move to a fix though.

**Comment by LeoGuanco** [comment]
@vabiro What I understood is that the FCM plugin uses an old google service version and so they conflict, if you're just going to use push notifications proba with the onesignal plugin
