### ISSUE TITLE
IOS can receive notification but on FCMPlugin.onNotification & data.wasTapped is not working [URGENT!!!!]

### ISSUE THREAD

**Issue by rehanhanar7** [fechanique/cordova-plugin-fcm#258]
Hello Everyone,

the FCm Plugin was working fine before. Now we are trying in IOS 10 version and above but the plugin is not working on IOS now. When app is in background or closed when i tap the notification i receive the app opens but the following function is not triggered in IOS alone. In android same code works fine. Kindly help in solving the issue

FCMPlugin.onNotification(
  function(data){
    if(data.wasTapped){
 alert("I am tapped" + data);
}
}function(msg){
 alert("I am tapped" + data);
  },
  function(err){
 alert("I am tapped" + data);
  });

**Comment by ferdil** [comment]
See my comment in issue #247 and my pull request #255

**Comment by rehanhanar7** [comment]
Hi actually i can receive notifications but i cant able to go inside the operations mentioned in the above code thats not working in IOS

**Comment by rehanhanar7** [comment]
When i tap on notification app opens but aleet doesnt comes. But in android it works perfectly

**Comment by rehanhanar7** [comment]
@ferdil I can able to receive the notification when i tap on the notification the app open success but the problem is once its opened as per the above code mentioned i am not getting the alert

**Comment by rehanhanar7** [comment]
@fechanique Could you please rerun the plugin and check and confirm ?

**Comment by BM9MobileBrasil** [comment]
@rehanhanar7 look at your code:
You are trying to access "msg" object at inexistent callbacks.
Try this:

`FCMPlugin.onNotification(function(data){
    if(data.wasTapped){
      alert("I am tapped" + JSON.stringify(data) );
    }else{
      //Notification was received in foreground. Maybe the user needs to be notified.
      alert( "I am tapped" +JSON.stringify(data) );
    }
});`

**Comment by rehanhanar7** [comment]
@BM9MobileBrasil Actually everything is properly written in code, I just mentioned example that which part of the code is not working, that Tap action is working on Android but its not working on IOS,

The below is the actual code. Its working fine in Android can u test in ur IOS device and tell me whether the alert is working or not.

FCMPlugin.onNotification(function(data){
    if(data.wasTapped){
            alert(JSON.stringify(data));
    }else{
             alert( JSON.stringify(data) );
    }
  },
  function(msg){
    console.log('onNotification callback successfully registered: ' + msg);
  },
  function(err){
    console.log('Error registering onNotification callback: ' + err);
  });

**Comment by rehanhanar7** [comment]
@BM9MobileBrasil I can receive notification in IOS but when i tap on the notification nothing works in IOS only not in Android

**Comment by Tobias4** [comment]
I have the same issue. Tested with iPad2 IOS 9.3.5
I am receiving notifications, if app is in background, but not if it is in forground. Tapping on notification opens app but onNotification is not called. Everything works perfect with android.

My code:
function onDeviceReady() {	
	FCMPlugin.onNotification(function(data){
		if(data.wasTapped){		  
		  .....
		} else {
		  .....		  
		}
	});	
}

**Comment by arthousecv** [comment]
My tests.
Android 4.2.2:  in background get push, after tap no alert, in foreground its ok
iPhone 5/7: work in background(after tap)/foreground
iPad 3, IOS 9.3.5: in background get push, after tap no alert, in foreground no alert

**Comment by themagicclicks** [comment]
Same test results as arthousecv above, Android working, iPhone 5s working, iPad 2 receives notification in background, but neither background tapped or foreground gets the onNotification activated, hence can't take any action onNotification on iPad

**Comment by rehanhanar7** [comment]
Hello @themagicclicks , @arthousecv  and others i have found a solution and fixed the issue for this currently am out of office i will update you guys on Monday. Have a happy weekend

**Comment by arthousecv** [comment]
Sounds good) Have a happy weekend

**Comment by ferdil** [comment]
Have a look at the code I've posted in issue #255

**Comment by rehanhanar7** [comment]
@ferdil .. In your code the tap action kind of works but 80% it fails and the app force closes. Kindly check the code

**Comment by rehanhanar7** [comment]
Hey everyone,

I fixed tap issue by installing the older version of plugin : cordova plugin add "cordova-plugin-fcm@1.1.5"

It works fine in Developer certificate but when i tried to build with enterprise certificate the plugin is not generating the token i tried looping set delays and everything still it didnt worked. In this older version of plugin there is no token refresh option so i am trying to implement the token refresh option. Because in the latest version i could able to receive the push token but i cant able to do tap action. So Certificate is fine. The plugin support for the enterprise certificate is not compatible on the older versions. But developer certificate works fine. While in the latest version tap action is not working. This is my last inference. I am trying to bring the token refresh option into the older version of the plugin. Let me know if you guys find any solution that will work on the enterprise certificate

**Comment by rehanhanar7** [comment]
Mistakenly closed the issue. The issue is not fixed yet

**Comment by rehanhanar7** [comment]
People for whom the push plugin works fine. Let us know the version of your plugin and if you guys have any solution let us know

**Comment by MeteorStartup** [comment]
@rehanhanar7 
yeah I think this is not clear yet.

I can't get the callback when the app was actually closed by exit() function.
it just process 'onNotification callback successfully registered' message (second argument of onNotification function) and do not trigger data callback.

is there any solution?

**Comment by rehanhanar7** [comment]
Yes data call back still not working trying to fix the plugin on my own will let u know if any update. In case if any guys came up with solution let me know

**Comment by alex3144** [comment]
Any body have find a solution for this bug ? 
thx all

**Comment by nicejwjin** [comment]
@rehanhanar7 cheer up bro~ lol~
I don't understand why this so important feature is not clear yet and no one comments out on it,
you're gonna save a lot of life if you fix this haha~

**Comment by tlebel** [comment]
@nicejwjin good point. that's why I decided to switch this morning to https://github.com/phonegap/phonegap-plugin-push and made it work on Android and iOS.  Better doc, better api, works well with Ionic 2 in my case.

**Comment by nicejwjin** [comment]
@tlebel Nice job. I'll figure out what can I do for this, works well with Meteor.js in my case haha. (Actually will be same issue though)

**Comment by rehanhanar7** [comment]
Hello Everyone,

Enterprise token generation is not working for IOS other than that other functionalities are working in the below old plugin version, We can also publish the app with Developer certificate for IOS so no need to worry about Enterprise certificate. Following is the solution which we have implemented in the application. Which is working both in IOS 9 and IOS 10 and above.

> cordova plugin add "cordova-plugin-fcm@1.1.5"

 Use this command to install the plugin all tap actions and everything is working fine except the token refresh function is absent in this version of plugin so u have to manually recall the gettoken function if the received token is null. Thats the solution for the problem. I would say this is a work around which i did to close this solution. The latest version of the plugin is still having other issues like tap action not working. So Hope developer has to fix. Until then use the above solution.

**Comment by rehanhanar7** [comment]
for IOS install this version of plugin

cordova plugin add "cordova-plugin-fcm@1.1.5"

Thats it. It will be fixed

**Comment by Anujmoglix** [comment]
I want's to do it for Ionic 3 , but i am not able to access callback message

```
  this.fcm.onNotification().subscribe(response => {
        alert("hello");
        alert( JSON.stringify(response) );
      if(response.wasTapped) {
      alert("Received in background");
      } else {
      alert("Received in foreground");
      };
    },
        msg =>{
            alert("error");
            alert(msg);
        });
```

**Comment by phieudu241** [comment]
I got the same issue again on iOS 10.3
Does anyone have a workaround for this?

**Comment by Anujmoglix** [comment]
I am also waiting for the workaround . i didn't get any solution of it.

**Comment by mora260** [comment]
Any solution to the newest version of the plugin?

**Comment by kirill-kostenetskyi** [comment]
Any updates on this ?

**Comment by wwwguy** [comment]
any update?

**Comment by ajay92x** [comment]
@ferdil I'm able to receive the notification and when i tap on the notification the app open but the problem is once its opened the onNotification does not trigger even when the app is in background or foreground in iOS 12.1. I'm using Ionic 4.

 As I'm using the latest fcm plugin so the solution mentioned in #247 is already in there so any suggestion.

**Comment by lucaslealdev** [comment]
Also having this problem (I'm using ionic if it makes any difference)

**Comment by rahulsharma841990** [comment]
@Anujmoglix : getting same issue.. did you find any solutions?

`2018-12-15 03:03:48.599716+0530 BeMeals[4536:1415669] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
`

**Comment by chitraguptpandey** [comment]
In the backend of my server, adding click_action parameter as FCM_PLUGIN_ACTIVITY, solves the issue for me! 
{
"notification":{
"title":"Notification title",
"body":"Notification body",
"sound":"default",
"click_action":"FCM_PLUGIN_ACTIVITY",
"icon":"fcm_push_icon"
}

**Comment by LeoProk** [comment]
https://github.com/fechanique/cordova-plugin-fcm/pull/339/commits this pull fixed the problem
