### ISSUE TITLE
Firebase Configuartion part in readme is very vague for someone which is new to fcm (or gcm)

### ISSUE THREAD

**Issue by RezaRahmati** [fechanique/cordova-plugin-fcm#26]
Firebase Configuartion part in readme is very vague for someone which is new to fcm (or gcm)
- For example how should we generate the files
- after generating how should we add them to cordova project?
- there are something on fcm site about editing build.gradle how we should do it in cordova

**Comment by wilsonpinto360** [comment]
@RezaRahmati you should follow firebase documentation to generate android/ios config files...and for the project itself, you should need install the plugin. It will do everything for you. Just test before open issue.

**Comment by sefsinalas** [comment]
I would like to implement notifications to my app but I dont understand how to use this plugin. Does anyone can share a link with a step by step tutorial?

**Comment by snehoo** [comment]
i used the steps given here for Ionic, worked great for me.
https://github.com/edismooth/ionic2-firebase/tree/master

**Comment by fechanique** [comment]
Please, Firebase configuration is well documented in their website

**Comment by RezaRahmati** [comment]
@wilsonpinto360 @fechanique Yes it's documented, but in this site documentation it says "copy 2 generated files", but I only get 1 and I don't know what is the next one, for making it more obvious at least you can name the files here, also when you create a project on FCM at the third step it says to add some lines of code in gradle.build it these steps necessary or not (this is another point that is vague) and then I get an error with message "Could not find method registerResGeneratingTask() for arguments" so I couldn't figure it out if am I missed one step in configurations or it's a bug or ...
It would be great if you could add some screenshots of step by step configuration

also it's not only my problem, look at @sefsinalas comment too

**Comment by RezaRahmati** [comment]
@snehoo Thanks

**Comment by RezaRahmati** [comment]
Or atleast you could add a sample project in the repo (or another one) and let people to figure out where exactly they should put the files or what changes is necessary to do
