### ISSUE TITLE
Notification Bar when app is not running (android)

### ISSUE THREAD

**Issue by roimekoi** [fechanique/cordova-plugin-fcm#263]
Hi, Thanks for this wonderful app..
I have an issue with the plugin for the push notification.
when the app is not running, i can still receive the push notification.
when i click on the push notification. it will launch the application.

for ios ,using ionic, i add deviceon onNotification inside app.js, i can still print the incoming message properly.
but for android it wont. 
i use adb logcat but it is not printing any incoming message.
do i need to implement something like broadcastreceiver?

Thanks and regards

**Comment by arthousecv** [comment]
Did you use firebase console for send notifications?
As i understand, for android, to get data after tap on notification (when app in background/closed) you need to post key "click_action" with value "FCM_PLUGIN_ACTIVITY", but in firebase there are no opportunity for this.
I try to use postman https://www.getpostman.com/ and its work

//POST: https://fcm.googleapis.com/fcm/send
//HEADER: Content-Type: application/json
//HEADER: Authorization: key=AIzaSy*******************
{
  "notification":{
    "title":"Notification title",
    "body":"Notification body",
    "sound":"default",
    "click_action":"FCM_PLUGIN_ACTIVITY",
    "icon":"fcm_push_icon"
  },
  "data":{
    "param1":"value1",
    "param2":"value2"
  },
    "to":"/topics/all",
    "priority":"high",
    "restricted_package_name":""
}

(cordova-plugin-fcm/REAMDE.md)

**Comment by roimekoi** [comment]
Hi, I manage to receive the message when i use my server to send the notification with FCM_PLUGIN_ACTIVITY ., 
May i know how can i set push notification rings. 
I only can do this if the app is running and i use local notification to set the sound effect.

regards
Ng
