### ISSUE TITLE
iOS not dealing  notification in background

### ISSUE THREAD

**Issue by andymoyle** [fechanique/cordova-plugin-fcm#265]
Using the cordova-pligin-fcm tester...
Testing on iphone 5c with dev cert uploaded to firebase. Can receive notifications fine, when in foreground. Xcode enabled Push and background...

Console.log is showing a notification is received while app in backround, but nothing on my phone and it seems FCMPlugin.onNotification is not firing. What have I coded wrong?

```
//FCMPlugin.onNotification( onNotificationCallback(data), successCallback(msg), errorCallback(err) )
				//Here you define your application behaviour based on the notification data.
				FCMPlugin.onNotification(function(data){
				
				console.log('Push:' +data);
    			if(data.wasTapped)
    			{
    					//Notification was received on device tray and tapped by the user.
      					navigator.notification.alert(data.aps.alert.body, null, data.aps.alert.title, 'OK');
	    			}else{
	    			
      					//Notification was received in foreground. Maybe the user needs to be notified.
						navigator.notification.alert(data.aps.alert.body, null, data.aps.alert.title, 'OK');
    				}
    			});

```

```
2017-03-02 15:23:44.182 WP Church[10099:2620423] app entered background
2017-03-02 15:23:44.185 WP Church[10099:2620423] Set state background
2017-03-02 15:23:44.186 WP Church[10099:2620423] Disconnected from FCM
2017-03-02 15:23:51.670: <FIRMessaging/WARNING> FIRMessaging receiving notification in invalid state 2
2017-03-02 15:23:51.670 WP Church[10099:2620423] Message ID: 0:1488468231367165%157d7ba0157d7ba0
2017-03-02 15:23:51.670 WP Church[10099:2620423] {
    aps =     {
        alert =         {
            body = "Testing in background";
            title = Testing;
        };
        badge = 0;
        category = "FCM_PLUGIN_ACTIVITY";
        "content-available" = 1;
        sound = default;
    };
    body = "Testing in background";
    "gcm.message_id" = "0:1488468231367165%157d7ba0157d7ba0";
    title = Testing;
}
```

**Comment by andymoyle** [comment]
Fixed itself - I was using Xcode7 so as still iPhone 4s compatible. 
Tried building in xCode 8 - total nightmare, couldn'tget it to run properly.
But build again on xCode 7 and now background works.

If anyone can explain that, I'd be grateful!!!

**Comment by ferdil** [comment]
It depends on which iOS SDK you've built with - what Base SDK version are you now using with XCode 7?

**Comment by mirulumam** [comment]
have you tried this? https://github.com/fechanique/cordova-plugin-fcm/issues/181 it works on my xcode 8 with iphone 9 iOS 10

**Comment by andymoyle** [comment]
In the end it was a provisioning profile issue. Once I had deleted them, restarted xcode, downloaded them, restarted xcode it all worked.

**Comment by saninaimayer** [comment]
I have the same error. My app receive and process notification in foreground but in background show this error: <FIRMessaging/WARNING> FIRMessaging receiving notification in invalid state 2.

My content-available set 1.

Please help me.
