### ISSUE TITLE
Can't send the message via mobile iOS

### ISSUE THREAD

**Issue by weboo1974** [fechanique/cordova-plugin-fcm#266]
Here is my code:

		var fcm_server_key = "AAAAu*****";
				
 		var notification_token = "ftXQkpueFkc*****";
		
		var notification_object = {		       
			"notification":{
		          "title":"Message from "+localStorage.getItem("user_name"),  //Any value
		          "body": msg,  //Any value
		          "sound": "default", //If you want notification sound
		        },
		        "data":{
				  "guest_id": guest_id,  //Any data to be retrieved in the notification callback 
				  "object_id": object_id,
				  "objectimg": objectimg,
				  "user_type": user_type
		        },
		        "priority":"high",
		        "content_available": true,
		        "to": notification_token, //Topic or single device
		        "restricted_package_name":""};       
		
		$$.ajax({
		  method: "POST",
		  headers: {'Content-Type': 'application/json', 'Authorization': 'key=' + fcm_server_key},
		  url: "https://fcm.googleapis.com/fcm/send",
		  data: notification_object,   
		  success: function(data) { 
			  alert("Success: " + JSON.stringify(data));
		  }, //on success      
		  error: function(data) {
		     alert("Error: " + JSON.stringify(data));
		  } //on error
		}, function(error){ console.error(error); });

I send notification via https://cordova-plugin-fcm.appspot.com/ and I can perfectly receive it in background or foreground mode. When I send it via mobile , I get "Success: id=0:1488*****" message, but it never arrives. What could be the problem? Help me please!!!!
Thank you!

**Comment by andymoyle** [comment]
The notification object needs to be JSON

So 
`data: JSON.stringify(notification_object),`

**Comment by weboo1974** [comment]
Thanks for your reply, but I already tried this, it didn't work.

**Comment by andymoyle** [comment]
And you have  $$.ajax - should be $.ajax in addition to JSON.Stringify the notification object
What console errors do you get?

**Comment by weboo1974** [comment]
$$ - it's ok, it's because I am using framework7 for developing frontend. I get no console errors.

**Comment by weboo1974** [comment]
I tried php to deliver the notifications, but no success a well:(

**Comment by weboo1974** [comment]
Somehow I managed to make it work in php, I am happy:)
