### ISSUE TITLE
User not receives notification message when application is killed

### ISSUE THREAD

**Issue by tolya199178** [fechanique/cordova-plugin-fcm#28]

**Comment by fechanique** [comment]
Make sure you are sending notifications using REST Service

**Comment by tolya199178** [comment]
I have sent via firebase console.
So I am sure there is no issue on sending notifications.
And I am receives notification when app is running or background.

**Comment by fechanique** [comment]
You can't use the Firebase Console, read the README please.

Firebase console does not have complete functionality, you must use REST API, see the payload example

**Comment by facuzeta** [comment]
"Firebase console does not have complete functionality..." that's right. I had some problems using the Firebase api with HTTP POST request. Finally I got it, I share here the python code to make notifications, that even works  if the app is killed. 

(Sorry if it is a bad place to share)


```python
import json
import urllib2

def send_notification_to_device(dst_fcm_token,api_key, title="",body="",sound="Default",data={}):
    post_args={}
    
    post_args['notification']={}
    post_args['notification']['title']=title
    post_args['notification']['body']=body
    post_args['notification']['sound']=sound
    post_args['notification']['click_action']='FCM_PLUGIN_ACTIVITY'
    
    post_args['data']=data
    
    post_args['to']=dst_fcm_token
    post_args['priority']='high'
    
    
    headers = {"Content-type": "application/json"}
    headers['Authorization']='key='+api_key
    
    req = urllib2.Request("https://fcm.googleapis.com/fcm/send")
    for k,v in headers.iteritems(): req.add_header(k,v) 
    r = urllib2.urlopen(req,data=json.dumps(post_fields))
    res = r.read()
    r.close()
    return res
```
