### ISSUE TITLE
Crash when app in foreground otherwise working

### ISSUE THREAD

**Issue by globules-io** [fechanique/cordova-plugin-fcm#293]
Tested on Android 6.0.1, Cordova 6.5.0 + Platform Android 6.2.2
Working as expected when app in not started or in the background
Crashes app if app is in the foreground when receiving a push

**Comment by globules-io** [comment]
Nevermind, a duplicate plugin caused the error

**Comment by netwrkx** [comment]
i'm also having the same challenge. push notification works in background but crashes the app when in foreground.
plugins
com-sarriaroman-photoviewer 1.1.10 "PhotoViewer"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-email 1.2.6 "EmailComposer"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-firebase 0.1.20 "Google Firebase Plugin"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

            FCMPlugin.onNotification(
                (data) => {
				console.log("data", data);
                    if(data.wasTapped){
                        //Notification was received on device tray and tapped by the user.
                        //alert( JSON.stringify(data) );
                    }else{
                        //Notification was received in foreground. Maybe the user needs to be notified.
                        //alert( JSON.stringify(data) );
                    }
                },
                (msg) =>{
                    console.log('onNotification callback successfully registered: ' + msg);
                },
                (err) =>{
                    console.log('Error registering onNotification callback: ' + err);
                }
            );
```
