### ISSUE TITLE
Get device token

### ISSUE THREAD

**Issue by glasset** [fechanique/cordova-plugin-fcm#3]
hello, 
There are no way to access on firebase token in javascript ?
I have to do implement a method like `sendRegistrationToServer(refreshedToken);` ?

**Comment by fechanique** [comment]
By the moment is not implemented, but you can subscribe the device to a topic and then send a notification to that topic you know, there is no limit on number of topics.

Next release (I think in a few days) will include a function to token access.

Regards,
    Felipe.

**Comment by bianchimro** [comment]
👍

**Comment by Windyuye** [comment]
👍

**Comment by jclalala** [comment]
:+1:

**Comment by coldcat-tw** [comment]
:+1:

**Comment by chris08002** [comment]
Great! Looking forward to it!

**Comment by fechanique** [comment]
Tomorrow this will be released
