### ISSUE TITLE
Ionic android project does not build

### ISSUE THREAD

**Issue by manjari-jayakumar** [fechanique/cordova-plugin-fcm#305]
Building an Ionic project fails with the following error:

BUILD FAILED

Total time: 2.835 secs

Error: /Users/manjari/RT-Hybrid-Mobile-App/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version
is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.andr
oid.gms to 9.0.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Ionic version:
============
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Not installed

Apparently google service plugin has a new version: 3.1.0 released on May 16th. The project is not compatible with the latest release version.

https://bintray.com/android/android-tools/com.google.gms.google-services

How to fix this?

**Comment by moonlitangel** [comment]
My solution : `.\plugins\cordova-plugin-fcm\src\android\FCMPlugin.gradle`

```
buildscript {
	repositories {
            jcenter()
			mavenLocal()
        }
    dependencies {
        classpath 'com.android.tools.build:gradle:+'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}
```

**Comment by parmindersingh1** [comment]
Same worked for me

**Comment by sasrinidhi** [comment]
This works. Thanks a lot.

**Comment by manjari-jayakumar** [comment]
Thanks a lot, It is working..
