### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by SmugbugsPravesh** [fechanique/cordova-plugin-fcm#307]
when we add this plugin, build will failed

Run with
BUILD FAILED

Total time: 3.433 secs
--stacktrace option to get the stack trace. Run with --info or --debug option to
 get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
> Execution failed for task ':processReleaseGoogleServices'.
> Please fix the version conflict either by updating the version of the google-s
ervices plugin (information about the latest version is available at https://bin
tray.com/android/android-tools/com.google.gms.google-services/) or updating the
version of com.google.android.gms to 9.0.0.

**Comment by larssn** [comment]
Solution here: https://github.com/fechanique/cordova-plugin-fcm/issues/306

**Comment by SmugbugsPravesh** [comment]
installes plugins
`com.hutchind.cordova.plugins.launcher 0.2.2 "Launcher"

cordova-plugin-camera 2.3.0 "Camera"

cordova-plugin-compat 1.1.0 "Compat"

cordova-plugin-device 1.1.3 "Device"

cordova-plugin-dialogs 1.3.3 "Notification"

cordova-plugin-facebook4 1.7.4 "Facebook Connect"

cordova-plugin-fcm 2.1.1 "FCMPlugin"

cordova-plugin-file 4.3.0 "File"

cordova-plugin-geolocation 2.4.3 "Geolocation"

cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"

cordova-plugin-network-information 1.3.0 "Network Information"

cordova-plugin-whitelist 1.3.0 "Whitelist"

cordova-plugin-x-toast 2.5.2 "Toast"

cordova.plugins.diagnostic 3.4.1 "Diagnostic"`

**Comment by vargaendre** [comment]
I got the same issue today and I don't know what was the trigger, honestly. It was working fine before.
@larssn 's solution does not work.
Please help

**Comment by SmugbugsPravesh** [comment]
use this plugin it work perfect with us
[cordova plugin add cordova-plugin-firebase](https://www.npmjs.com/package/cordova-plugin-firebase)

**Comment by larssn** [comment]
We experienced crashes with that plugin, so we stopped using it. See https://github.com/arnesson/cordova-plugin-firebase/issues/270

**Comment by vargaendre** [comment]
OK, so @larssn 's idea DOES work, I was first editing the wrong file, then forgot to remove/readd platform. Thanks.

**Comment by SmugbugsPravesh** [comment]
[works for me too](https://github.com/fechanique/cordova-plugin-fcm/issues/306#issuecomment-302060996)
