### ISSUE TITLE
iOS : invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options

### ISSUE THREAD

**Issue by JCornat** [fechanique/cordova-plugin-fcm#308]
Hello,

I have a Firebase project where I have downloaded the iOS and Android configuration files.
It works on Android, but on iOS launch, the app just crashes and here is the log.

I have checked the GoogleService-Info.plist, re-downloaded, but everytime, I got this error.

```2017-05-17 12:06:45.521: <FIRMessaging/INFO> FIRMessaging library version 1.2.0
2017-05-17 12:06:45.541 BioContact[4304] <Debug> [Firebase/Core][I-COR000001] Configuring the default app.
2017-05-17 12:06:45.542 BioContact[4304] <Error> [Firebase/Core][I-COR000009] The GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid. If you are using the plist file, use the iOS version of bundle identifier to download the file, and do not manually edit the GOOGLE_APP_ID. You may change your app's bundle identifier to '(null)'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
2017-05-17 12:06:45.547 BioContact[4304:6763094] *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010705db0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000106a99141 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001070c6625 +[NSException raise:format:] + 197
	3   BioContact                          0x0000000105f0598d +[FIRApp addAppToAppDictionary:] + 371
	4   BioContact                          0x0000000105f04f38 +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 285
	5   BioContact                          0x0000000105f04c6c +[FIRApp configure] + 302
	6   BioContact                          0x0000000105ea49ff -[AppDelegate(MCPlugin) application:customDidFinishLaunchingWithOptions:] + 767
	7   UIKit                               0x0000000107e36957 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 299
	8   UIKit                               0x0000000107e3823c -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4119
	9   UIKit                               0x0000000107e3e584 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
	10  UIKit                               0x0000000107e3b793 -[UIApplication workspaceDidEndTransaction:] + 182
	11  FrontBoardServices                  0x000000010c7b45f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	12  FrontBoardServices                  0x000000010c7b446d -[FBSSerialQueue _performNext] + 186
	13  FrontBoardServices                  0x000000010c7b47f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	14  CoreFoundation                      0x0000000107003c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	15  CoreFoundation                      0x0000000106fe90cf __CFRunLoopDoSources0 + 527
	16  CoreFoundation                      0x0000000106fe85ff __CFRunLoopRun + 911
	17  CoreFoundation                      0x0000000106fe8016 CFRunLoopRunSpecific + 406
	18  UIKit                               0x0000000107e3a02f -[UIApplication _run] + 468
	19  UIKit                               0x0000000107e400d4 UIApplicationMain + 159
	20  BioContact                          0x0000000105dc40a1 main + 65
	21  libdyld.dylib                       0x000000010986c65d start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

```

Can you help me understand why Firebase crashes on iOS ? 

Thank you !

**Comment by larssn** [comment]
`GoogleService-Info.plist` usually becomes corrupted for whatever reason.

Check `platforms/ios/<Your Project>/Resources/` and `platforms/ios/<Your Project>/Resources/Resources`

There should be a `GoogleService-Info.plist` in both locations. One of these should be corrupt. Usually its the one furthest in.

Replace that one, and it should work.

**Comment by JCornat** [comment]
I have replaced the file in both folders and it works, thank you !

**Comment by codinronan** [comment]
Wow this is obscure and even more amazing that someone knew the solution. You just saved me... countless hours, @larssn .

**Comment by nitin7dc** [comment]
@larssn super thanks !

**Comment by rolinger** [comment]
holy sweet jesus batman!!!!!!!!!  Like @codinronan said, this completely obscure solution fixed my issue.  and I am not even using the FCM plugin, I am using the Firebase plugin.  Rebuilt my app project from scratch and the problem still persisted...until I found this solution!!!!  

thank you....Thank You....THANK YOU!!!!

**Comment by shanmicheal25** [comment]
Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'
*** First throw call stack:
(0x184096fe0 0x182af8538 0x184096f28 0x100145600 0x100144ba8 0x1001448d0 0x1000c16c0 0x18a239e48 0x18a44637c 0x18a44be24 0x18a4608b0 0x18a4490b8 0x185c40884 0x185c406f0 0x185c40aa0 0x18404542c 0x184044d9c 0x1840429a8 0x183f72da4 0x18a232fc8 0x18a22dc9c 0x1000bee34 0x182f8159c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vancarney** [comment]
@shanmicheal25 be sure to overwrite the .plist file under platforms/ios/<Your Project>/Resources/Resources with the .plist file from your root

At least that made all the difference to me

**Comment by Junior-iOS** [comment]
Sorry, guys.
Where do I find the path platforms/ios?

**Comment by satryacode** [comment]
@Junior-iOS it's in <cordova project root folder>
the folder created after you add platform in it
by running this command in your console `cordova platform add ios`

**Comment by PredragJ** [comment]
For Xcode 9, solution is to check box <yourProject> at Target Membership Tab on GoogleService-Infp.plist

**Comment by Geeksquid04** [comment]
where do you find the platforms folder?

**Comment by sKuD51** [comment]
Same problem, I dont know why, but I replace my olds GoogleService-Info.plist in : 
- root folder
- /platforms/ios/yourAppNameFolder/Resources
- /platforms/ios/yourAppNameFolder/Resources/Resources

It works fine.

**Comment by Jhonsensf** [comment]
Same problem here. I replaced the files and it is working fine.

Thank you!

**Comment by TheNaderio** [comment]
In this File was no Informations:
/platforms/ios/yourAppNameFolder/Resources/Resource/GoogleService-Info.plist

So i copyed 
this -> /platforms/ios/yourAppNameFolder/Resources/GoogleService-Info.plist
to here -> /platforms/ios/yourAppNameFolder/Resources/Resource/GoogleService-Info.plist

**Comment by Xam-Devender** [comment]
Thanks !!!!!!!!! Re-Downloaded -> Build and that's all it worked ... :)

**Comment by roshandhabekar** [comment]
hello @larssn ,
I  am building ionic ios,
i got the file at ,
 /platforms/ios/yourAppNameFolder/Resources/GoogleService-Info.plist

but I don't have resources folder inside resources,
/platforms/ios/yourAppNameFolder/Resources/Resource/GoogleService-Info.plist
Can you please suggest me, which one should I replace.


Thanks!

**Comment by vanschroeder** [comment]
@roshandhabekar per the other comments above, just create the missing Resources folder and copy the GoogleService-info.plist file into place. If that doesn't work I would suggest `ionic cordova platform rm ios` and `ionic cordova platform add ios` which is typically an expedient way to correct platform specific issues

**Comment by jonathan-chin** [comment]
Thanks @larssn ! indeed, the deeper plist file was empty.

Any idea why this happens?

**Comment by larssn** [comment]
@jonathan-chin I haven't digged into the code; I assume there's a bug in there somewhere.

**Comment by edugolive** [comment]
I found the problem.
These plugins, as well as the cordova-plugin-firebase, have the after-ready script, in this case scripts/fcm_config_files_process.js, which at line 20 tries to get the name of the project in this way (var name = getValue (config, 'name');).
And in the "getValue" method it tries to read the <name> tag of the config.xml file.
That way (var value = config.match (new RegExp ('<' + name + '> (. *?) </' + Name + '>', 'i'));).
So if your config.xml file is described this way <name>MyAppName</ name>, this will work.
Now if so, <name shortName="AnyName">MyAppName</ name> will return as null.
That way when the rest of the script tries to do this (IOS_DIR + '/' + name + '/Resources/GoogleService-Info.plist'), this will result in "ios/null/Resources/GoogleService-Info.plist" that does not exist, and will not save the file.

Then leave the <name> tag of config.xml in this way <name>MyAppName</name> and it will work.
Hug.

**Comment by coolvasanth** [comment]
I just removed the GoogleService-info.plist file from my project root folder and re added it, everything works fine now.

**Comment by robertohuertasm** [comment]
Why is this thread closed? It seems that the issue is still going on...

**Comment by mohitcis** [comment]
@larssn thanks, It worked for me :)

**Comment by madhurakhal** [comment]
I am having same problem. adding Resource with GoogleService-info.plist does not solve the problem. I am using XCode 10.1

**Comment by sibabratswain11** [comment]
@madhurakhal  did you find any solution ?

**Comment by edugolive** [comment]
My tip is you start from scratch.
Delete all your android sdk files. open the android studio and download again the versions of sdk you need.
Delete your files from the node_modules folder and download it again.
Remove your plugins used in the project and download it again.
Build project again.
It worked for me.

**Comment by aryeharmon** [comment]
how can i add this solution to the config.xml?

**Comment by RashedulAlam** [comment]
Is there any possible solutions ? i just got tired with this

**Comment by avaiyakirtib** [comment]
Replacing the .plist from `platforms/ios/<Your Project>/Resources/ ` solved my problem

**Comment by devjva** [comment]
Change the file permissions of the entire project, some files were read only.
it worked for me

**Comment by jdavidteki** [comment]
Is anyone getting this issue while using react-native?

**Comment by shabeer3508** [comment]
> In this File was no Informations:
> /platforms/ios/yourAppNameFolder/Resources/Resource/GoogleService-Info.plist
> 
> So i copyed
> this -> /platforms/ios/yourAppNameFolder/Resources/GoogleService-Info.plist
> to here -> /platforms/ios/yourAppNameFolder/Resources/Resource/GoogleService-Info.plist

you saved my day

**Comment by GiladR1979** [comment]
> Is anyone getting this issue while using react-native?

Yes. This is not solved yet. 
I get a crash on +[FIRApp addAppToAppDictionary:], using +[FIRApp configureWithOptions:] and specifying the .plist file (I have multiple schemes and targets).
Weirdly it only crashes when downloading app from TestFlight and not running with XCode, and only on old iPhones- iPhone 5,6,7.

**Comment by TylerByte666** [comment]
This still works as of 19/12/2019 you just made my Christmas ❤️ 
Thanks @larssn 🥇

**Comment by cyonusg** [comment]
2020 and works yet !! @larssn

**Comment by mikeCm14** [comment]
2020 in quarantine and the issue still exists and the workaround still works. 
Thank you, @larssn
Maestro 🙌🏻

**Comment by kapilSoni101** [comment]
@larssn :i tried but its not working for me

**Comment by yellaiahd** [comment]
Dwonload from firebase console and place in. platforms/ios/<Your Project>/Resources/  its resolved.

**Comment by ikishanoza** [comment]
I am using capacitor so there is no folder called "Resources" I have tried every solution which is mentioned here still having same issue. i am using lastest xcode version.

**Comment by itshazlan** [comment]
> I am using capacitor so there is no folder called "Resources" I have tried every solution which is mentioned here still having same issue. i am using lastest xcode version.

same here still waiting for someone to solve this

**Comment by wlofgren** [comment]
i'm getting the same error using capacitor.

[Firebase/Core][I-COR000009] The GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid. If you are using the plist file, use the iOS version of bundle identifier to download the file, and do not manually edit the GOOGLE_APP_ID. You may change your app's bundle identifier to '(null)'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.

 *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'

**Comment by Melf11** [comment]
for **Capacitor** replace 
`/ios/capacitor-cordova-ios.plugins/resources/GoogleService-Info.plist`

**Comment by Shery11** [comment]
> for **Capacitor** replace `/ios/capacitor-cordova-ios.plugins/resources/GoogleService-Info.plist`

This doesn't work. I am using capacitor and the latest code.

**Comment by felix-mittermeier** [comment]
If you still have this issue and replacing the files did not work make sure that your appID set in your custom options at Firebase.init really do match their specific platform.
The appIds look very similar to each other but are indeed DIFFERENT for every platform (iOS, Android, Web). So make sure to check the platform first and then set the corresponding id at the options.

**Comment by RomanSoviak** [comment]
If you develop the app on Flutter inside FirebaseOptions object you should differentiate this parameter:


```
...
  appId: Platform.isIOS
          ? "1:639*****:ios:e0*********"
          : "1:639******:android:032bd**********",
```

**Comment by EduardoIbarra** [comment]
> for **Capacitor** replace `/ios/capacitor-cordova-ios.plugins/resources/GoogleService-Info.plist`

This did the trick for me. The file was there, but didn't have any property.
