### ISSUE TITLE
getToken not working

### ISSUE THREAD

**Issue by raidhon** [fechanique/cordova-plugin-fcm#314]
Function FCMPlugin.getToken() stopped working.
More precisely began to return null.
Apparently, the update firebase api.
Please update the plugin!

**Comment by raidhon** [comment]
Fixed

**Comment by yosranagati** [comment]
how did you fixed it same issue here

**Comment by raidhon** [comment]
@yosranagati 
classpath 'com.google.gms:google-services:+'
replace
`classpath 'com.google.gms:google-services:3.0.0'`

Here is already fixed.
Moreover, in may

**Comment by NileshSystematix** [comment]
I am also facing the same issue getToken method is not called
