### ISSUE TITLE
Android Build failed: processdebuggoogleservices 

### ISSUE THREAD

**Issue by Ratnesh-K** [fechanique/cordova-plugin-fcm#321]
Hello ,

  I am implementing google map and FCM in single project i have added google maps its working but i have added the FCM plugin its not working getting version conflicts in project Following error i am getting 

Error:Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

**Comment by gljacobs** [comment]
+1

**Comment by januarsy** [comment]
Edit file,
??-FCMPlugin.gradle 
(Location file : platforms/android/cordova-plugin-fcm/??-FCMPlugin.gradle)

`buildscript {`
`repositories {`
`jcenter()`
`mavenLocal()`
`}`
`dependencies {`
`classpath 'com.android.tools.build:gradle:+'`
`classpath 'com.google.gms:google-services:3.0.0'` // Replace + to 3.0.0

**Comment by Ratnesh-K** [comment]
FCMPlugin.gradle
(Location file : platforms/android/cordova-plugin-fcm/??-FCMPlugin.gradle)

buildscript {
repositories {
jcenter()
mavenLocal()
}
dependencies {
classpath 'com.android.tools.build:gradle:+'
classpath 'com.google.gms:google-services:3.0.0' 

Updated 

Still i am facing issue : 
Error:Cannot add task ':processDebugGoogleServices' as a task with that name already exists.

this is my Project gradle :

  dependencies {
        classpath 'com.android.tools.build:gradle:2.2.1'
        classpath 'com.google.gms:google-services:3.0.0'
    }

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v4:+"
    compile "com.android.support:appcompat-v7:+"
    compile 'com.facebook.stetho:stetho-okhttp:1.2.0'
    compile "com.google.android.gms:play-services-maps:9.8.0"
    compile "com.google.android.gms:play-services-location:9.8.0"
    compile "com.google.firebase:firebase-core:+"
    compile "com.google.firebase:firebase-messaging:+"
    // SUB-PROJECT DEPENDENCIES END
}
apply plugin: "com.google.gms.google-services"

**Comment by Boamorte8** [comment]
+1

I resolve this, change 
`classpath 'com.google.gms:google-services:+'`
for this
`classpath 'com.google.gms:google-services:3.0.0'`

In the files _FCMPlugin.gradle_ and _app-FCMPlugin.gradle_

**Comment by Ratnesh-K** [comment]
Its still not resolved its getting issue with 

Please fix the version conflict either by updating the version of the google-services plugin

**Comment by januarsy** [comment]
I advise you to remove cordova-plugin-fcm plugin and use this plugin
**cordova-plugin-firebase-extended-notification**

**Comment by Ratnesh-K** [comment]
Hey @januarsy ,

    Thank you so much its working fine
