### ISSUE TITLE
Can't subscribe to topics on ios (Error Domain=com.google.fcm Code=5)

### ISSUE THREAD

**Issue by neilmctee** [fechanique/cordova-plugin-fcm#36]
I get the following error when attempting to subscribe to any topic on ios....

`<FIRMessaging/WARNING> Failed to subscribe to topic Error Domain=com.google.fcm Code=5 "(null)"`

It's worth noting that I _am_ able to retrieve an FCM token.

Any ideas?

**Comment by aparedes** [comment]
are you using the simulator? it only works in a device

**Comment by neilmctee** [comment]
No, I'm using a device.

I am able to send send push notifications directly to the device using the token (which would indicate set-up / certificates etc is ok) - I just can't subscribe to any topics.

**Comment by jtwiest** [comment]
I ran into this as well, I believe I fixed this by including this field in my info.plist file:

FirebaseAppDelegateProxyEnabled: YES

If that doesn't work could you provide the rest of of the xcode console output? Better if you turn debugging for Firebase on using this:

`To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)`

**Comment by neilmctee** [comment]
Turns out this is an issue with FCM and not the plugin. Basically subscribing to multiple topics fails. A workaround is to put a short delay between subsequent subscription calls.

See [http://stackoverflow.com/questions/37372806/firebase-cloud-messaging-and-multiple-topic-subscription-from-ios-fails](url) for details.

**Comment by bmwertman** [comment]
I'm having this issue but @neilmctee SO link seems to have been taken down. It returns a 404.

**Comment by atlanteh** [comment]
The text is right, the hypertext is broken:
http://stackoverflow.com/questions/37372806/firebase-cloud-messaging-and-multiple-topic-subscription-from-ios-fails

**Comment by liuyanhongwl** [comment]
thank you. a short delay is useful for me.

**Comment by revolter** [comment]
There is already an issue [here](https://github.com/firebase/quickstart-ios/issues/146).

**Comment by kddior** [comment]
fixed it by setting FirebaseAppDelegateProxyEnabled to  YES thanks  @jtwiest

**Comment by bhooshanpatil** [comment]
a little delay helped..

**Comment by Anujmoglix** [comment]
Hi all ,
I am getting issue Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"

var myTopics = "all";
      this.fcm.subscribeToTopic(myTopics).then(success => {
          console.log("***Here is success****"+success); alert(success) },
              error => { console.log("***This is the issue****"+error); alert(error);})
          .catch(response => {
              alert(response);
              console.error('Gists error = ', response);
          });

**Comment by kapilSoni101** [comment]
@jtwiest:sir are u fixed above issue after put FirebaseAppDelegateProxyEnabled: YES?

**Comment by KetanMalu** [comment]
Hello All,
We are using Firebase to send notifications to users.Normal push notifications are receiving to device, only firebase topics notification not receiving.iPhone 6 Plus, iPhone 8 are receiving firebase topics notifications only iPhone X not receiving firebase topics notification. I am not able to understand code is working for two devices then why iPhone X not receiving topics notification. 

- As suggested I have added delay but didn't worked for me. 
- FirebaseAppDelegateProxyEnabled to YES didn't worked

iPhone X OS Version - 12.4.1 
FirebaseMessaging version - 3.5.0

After started printing firebase logs in XCODE found following log for iPhone X

[Firebase/Messaging][I-FCM004001] Failed to subscribe to topic Error Domain=com.google.fcm Code=501 "(null)"

Please guide. Thanks In advance.
