### ISSUE TITLE
Android notification bar icon is blank square

### ISSUE THREAD

**Issue by amit777** [fechanique/cordova-plugin-fcm#367]
I put the icon in resources/android/icon/fcm_push_icon.png

Here is the info about the PNG:
```
identify resources/android/icon/fcm_push_icon.png

resources/android/icon/fcm_push_icon.png PNG 96x96 96x96+0+0 8-bit sRGB 2.53KB 0.000u 0:00.009
```

When I run "ionic prepare" or "cordova prepare", I don't see the file get copied into the platforms/android directory anywhere.  Is there some specific place I need to put it manually?

**Comment by amit777** [comment]
I tried copying the file to:
platforms/android/res/fcm_push_icon.png

and then rebuilding and running.. No luck.

**Comment by amit777** [comment]
so I needed to put the icon inside platforms/android/res/mimap-xxxhdpi/fcm_push_icon.png

that seems to work.

**Comment by cikcoh** [comment]
Hi @amit777  i tried that but my app still uses default ionic icon. 
![screenshot_2018-03-07-17-28-31-357_com miui home](https://user-images.githubusercontent.com/37142659/37088961-fed2c258-2239-11e8-9f9a-d724f5d55ff2.png)

`        data: JSON.stringify(
            {
              "notification":{
                "title":"Help",  //Any value
                "body": pointA,  //Any value
                "sound": "siren1", //If you want notification sound
                "click_action": "FCM_PLUGIN_ACTIVITY",  //Must be present for Android 
                "icon": "fcm_push_icon" , //White icon Android resource
                "color": '#6563A4',
              },
              "data":{
                "param1":lat,  //Any data to be retrieved in the notification callback
                "param2":lng,
                "param3":address,
              },`
![capture](https://user-images.githubusercontent.com/37142659/37088662-105ab5fe-2239-11e8-98c8-fc05fd939312.PNG)
Do ypu have any idea why?
Thanks.
