### ISSUE TITLE
onNotification callback not fired when comming from device tray.

### ISSUE THREAD

**Issue by benc1** [fechanique/cordova-plugin-fcm#37]
FCMPlugin.onNotification(
                function (data) {
                    log(JSON.stringify(data));
                },
                function success(data) {
                    log('success:' + JSON.stringify(data));
                },
                function error(data) {
                    log('error:' + JSON.stringify(data));
                }
            );
The first callback function is not called when comming from device tray

**Comment by Captnwalker1** [comment]
Did you fix this? I am having the same issue on android

**Comment by mirulumam** [comment]
same here. can you please explain how to fix this? thanks
