### ISSUE TITLE
Data messages - FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by CowboyCode** [fechanique/cordova-plugin-fcm#375]
Data message are not received, related to upgrades ios sdk

Methods need to be implemented as on the firebase page.
I have upgraded the ios sdk and renamed deprecated methods but I am not an objective-c programmer and need some help here.

https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Protocols/FIRMessagingDelegate#-messagingdidreceivemessage

My current clean and upgraded fork is at
https://github.com/ostownsville/cordova-plugin-fcm

**Comment by chrisjpalmer** [comment]
Hi @CowboyCode I have had a crack at it. I realised I changed a lot of the code and that is because it seems that the new version of Firebase SDK did a lot more stuff on behalf of the programmer. Thus there is no need to establish a connection with Firebase as the docs explain this is totally handled by Firebase SDK.

Have a look at the way the docs tell you to setup the connection with Firebase: https://firebase.google.com/docs/cloud-messaging/ios/client 

Also I have given up supporting < IOS 9 because I don't think you can even compile the latest cordova projects for those iOSs anyway. Correct me if I'm wrong.

I have not tested any of this code because I don't have my iPhone but if someone wants to have a go, be my guest. Otherwise I will be able to test in the next 2-3 days.

https://github.com/chrisjpalmer/cordova-plugin-fcm

**Comment by CowboyCode** [comment]
@chrisjpalmer 
I'll check that out tomorrow morning, thanks :-)

**Comment by CowboyCode** [comment]
@chrisjpalmer @1N50MN14
I just tested your repo Chris....
It works 👍  

One minor warning, otherwise, I have received notifications and pure messages, great job :-)

![screen shot 2017-09-06 at 8 05 22 am](https://user-images.githubusercontent.com/24927350/30085582-7eb8d6c8-92da-11e7-8099-8bbc22e68925.png)

**Comment by 1N50MN14** [comment]
Wait wait how did I miss @chrisjpalmer's post! Wow going to give it a shot right away!! @CowboyCode  :)

**Comment by chrisjpalmer** [comment]
Thats fantastic! Check out my comments inside the AppDelegate+FCMPlugin.m. There are a few cases I'm not 100% sure of yet. Also yes I don't understand why that compiler warning is coming up because there is no duplicate method anywhere. I will have another look just in case.

**Comment by chrisjpalmer** [comment]
Fixed the compiler warning check the repo. Do you want me to put up a PR?

**Comment by 1N50MN14** [comment]
@chrisjpalmer this is awesome thank you!! having some USB issues will test again in 6-8 hours (4am over here) and post back :) 

// cc @CowboyCode PR

**Comment by CowboyCode** [comment]
@chrisjpalmer PR, yes, go for it

**Comment by chrisjpalmer** [comment]
https://github.com/ostownsville/cordova-plugin-fcm/pull/4

**Comment by CowboyCode** [comment]
Merged

**Comment by 1N50MN14** [comment]
@CowboyCode @chrisjpalmer I've been testing the merged update today (apologies it took some time, it wasn't my USB, had to buy a new iPhone grr). So now the XCode error is gone but for some reason data notifications are not being caught & forwarded to the app... push notifications work just fine... does data notification work for you and if so how does the message look like?

**Comment by 1N50MN14** [comment]
Hey guys! I thought I'd add the plugin from @chrisjpalmer's repo and it did work! 

This is *strange*, @CowboyCode are you sure the PR was merged correctly?

**Comment by chrisjpalmer** [comment]
Well @CowboyCode has updated the Firebase SDK to the latest version which is the difference between my repo and his at the moment.

**Comment by 1N50MN14** [comment]
Interesting, which version are you running / how old is it if I may ask? XCode is not throwing an errors; the "didReceiveMessage" thing is recent so it should've worked with @CowboyCode repo as well..

**Comment by chrisjpalmer** [comment]
It was at v 4.0.0 and now its at 4.1.1

https://github.com/ostownsville/cordova-plugin-fcm/pull/6

**Comment by chrisjpalmer** [comment]
I will check this out later today and test for myself as well.

**Comment by 1N50MN14** [comment]
That would be great thank you @chrisjpalmer!

**Comment by chrisjpalmer** [comment]
Hi @1N50MN14. I gave it a test myself this afternoon.

This is what I have found:
Tested on iOS 10.3.3 w. from current ostownsville master branch
- Data only notifications are propagating through the messaging:didRecieveMessage: handler
- Normal notifications are propagating through the iOS 10 notification center handlers

**Data only message:**
```
APPLOG => messaging:didReceiveMessage:remoteMessage:
APPLOG => Notification Data: <7b224455 4d4d5922 3a224441 5441222c 22636f6c 6c617073 655f6b65 79223a22 636f6c6c 61707365 222c2277 61735461 70706564 223a6661 6c73652c 2266726f 6d223a22 32343934 33363639 38343832 227d>
APPLOG => notifyOfMessage: => executing javascript callback
APPLOG => stringByEvaluatingJavaScriptFromString FCMPlugin.onNotificationReceived({"DUMMY":"DATA","collapse_key":"collapse","wasTapped":false,"from":"249436698482"});
```

**Notification message:**
```
APPLOG => userNotificationCenter:willPresentNotification:withCompletionHandler:
APPLOG => Notification Data: <7b226763 6d2e6d65 73736167 655f6964 223a2230 3a313530 35313036 33323133 32353139 36256663 39326236 61316663 39326236 6131222c 2244554d 4d59223a 22444154 41222c22 77617354 61707065 64223a66 616c7365 2c226170 73223a7b 22616c65 7274223a 7b227469 746c6522 3a224a6f 62203735 3a204e65 7720436f 6d6d656e 74222c22 626f6479 223a2253 75706572 20557365 723a2048 656c6c6f 227d7d7d>
APPLOG => notifyOfMessage: => executing javascript callback
APPLOG => stringByEvaluatingJavaScriptFromString FCMPlugin.onNotificationReceived({"gcm.message_id":"0:1505106321325196%fc92b6a1fc92b6a1","DUMMY":"DATA","wasTapped":false,"aps":{"alert":{"title":"75: New Comment","body":"Super User: Hello"}}});
```

**Notification message tapped from notification centre:**
```
APPLOG => applicationDidEnterBackground:
APPLOG => userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:
APPLOG => Notification Data: <7b226763 6d2e6d65 73736167 655f6964 223a2230 3a313530 35313036 34313137 36363935 36256663 39326236 61316663 39326236 6131222c 2244554d 4d59223a 22444154 41222c22 77617354 61707065 64223a74 7275652c 22617073 223a7b22 616c6572 74223a7b 22746974 6c65223a 224a6f62 2037353a 204e6577 20436f6d 6d656e74 222c2262 6f647922 3a225375 70657220 55736572 3a204865 79204348 72697322 7d7d7d>
APPLOG => notifyOfMessage:withTapInfo: => wasTapped = true... therefore going to store the data and send when app returns to the foreground

APPLOG => applicationDidBecomeActive:
APPLOG => notifyOfMessage: => executing javascript callback
APPLOG => stringByEvaluatingJavaScriptFromString FCMPlugin.onNotificationReceived({"gcm.message_id":"0:1505106411766956%fc92b6a1fc92b6a1","DUMMY":"DATA","wasTapped":true,"aps":{"alert":{"title":"75: New Comment","body":"Super User: Hey Chris"}}});
```

**Comment by 1N50MN14** [comment]
Hi @chrisjpalmer,

Thank you very much for testing it! This is strange indeed because I'm receiving similar output excepting zero logs for data only message, yeah the base SDK is set to iOS 10.3 I'm not supporting older versions.

hmmm I wonder if I should manually clean up and try again, I'll give it a go, if @CowboyCode's repo works for you then the only thing I could think of is that it must a local clean up / mismatch issue possibly with the FCM SDK..
