### ISSUE TITLE
Not receiving notification in background for Android

### ISSUE THREAD

**Issue by Aunt-Buttons** [fechanique/cordova-plugin-fcm#384]
Hi,

I have managed to receive notifications on pause & when the project is in the foreground, but once I've killed the app I do not receive any notification via firebase on my physical android device.

My code is listed below. Any suggestions on what it could be?

Thanks,

Ionic v2 code below:

constructor(
  ....
  public fcm: FCM
  ){
    platform.ready().then(() => {
      statusBar.styleDefault();
      splashScreen.hide();

      document.addEventListener("pause", function(event) {
        console.log("pause");
      }, false);

      document.addEventListener("resume", function(event) {
        console.log("Resume");
      }, false);

      document.addEventListener("backbutton", function(event) {
        console.log("Back button");
      }, false);
    });

    this.pushNotification();
  }

  pushNotification() {
    this.fcm.onNotification().subscribe(data => {
      if (data.wasTapped) {
        //Notification was received on device tray and tapped by the user.
        console.log(data);
    } else {
        //Notification was received in foreground. Maybe the user needs to be notified.
        console.log(data);
    }
    });
  }

Notification Firebase Post:

let notification = {
      "to": "/topics/test",
      "priority": "high",
      "content_available": true,
      "notification": {
        "title": "Notification title",
        "body": "Notification body",
        "sound": "default",
        "click_action": "FCM_PLUGIN_ACTIVITY",
        "icon": "fcm_push_icon"
      },
      "data": {
        "title": "New Message",
        "body": "New message received!"
      }
    };
    let headers = new Headers;
    headers.append('Content-Type', 'application/json');
    headers.append('Authorization', 'key=myKey' );
    this.http.post('https://fcm.googleapis.com/fcm/send', notification, {headers: headers} )
      .subscribe(res => {
        console.log(res);
      });

**Comment by Aunt-Buttons** [comment]
Figured out my problem.
I'm running it on an Asus phone, which requires auto-start to accept the app.

**Comment by skssurendra008** [comment]
Hi,
The problem seems to be solved if you add the following in the payload’s notification object:
click_action:"FCM_PLUGIN_ACTIVITY".

var payloadOK = {
    to: validDeviceRegistrationToken,
    notification: { //notification object
        title: 'Suri', body: 'World!', sound : "default", badge: "1", click_action:"FCM_PLUGIN_ACTIVITY"
    },
    data: { //some data object (optional)
        url: 'news',
        foo:'fooooooooooooo',
        bar:'bar bar bar'
    },
    priority: 'high',
    content_available: true
};
