### ISSUE TITLE
Cannot find framework FirebaseAnalytics.framework" for plugin          cordova-plugin-fcm in iOS platform

### ISSUE THREAD

**Issue by roberthgodoy** [fechanique/cordova-plugin-fcm#393]
cordova platform add ios --save
✖ Running command - failed!
[ERROR] Exception: Using cordova-fetch for cordova-ios@~4.5.1

        Adding ios project...
        Creating Cordova project for the iOS platform:
        	Path: platforms/ios
        	Package: com.br.duogourmet
        	Name: Duo Gourmet
        iOS project created with cordova-ios@4.5.2
        Installing "cordova-plugin-camera" for ios
        Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
        Installing "cordova-plugin-compat" for ios
        Dependent plugin "cordova-plugin-compat" already installed on ios.
        Installing "cordova-plugin-console" for ios
        Installing "cordova-plugin-device" for ios
        Installing "cordova-plugin-fcm" for ios
        Error during processing of action! Attempting to revert...
        Failed to install 'cordova-plugin-fcm': CordovaError: Uh oh!
        Cannot find framework "/Users/NIlson-mac/Desktop/APPS DUO 
        GOURMET/duo-gourmet-app/plugins/cordova-plugin-fcm/src/ios/firebase/FirebaseAnalytics.framework" for plugin 
        cordova-plugin-fcm in iOS platform
             at install (/Users/NIlson-mac/Desktop/APPS DUO 
        GOURMET/duo-gourmet-app/platforms/ios/cordova/lib/plugman/pluginHandlers.js:109:48)
             at ActionStack.process (/Users/NIlson-mac/Desktop/APPS DUO 
        GOURMET/duo-gourmet-app/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
             at PluginManager.doOperation (/Users/NIlson-mac/Desktop/APPS DUO 
        GOURMET/duo-gourmet-app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
             at PluginManager.addPlugin (/Users/NIlson-mac/Desktop/APPS DUO 
        GOURMET/duo-gourmet-app/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
             at Api.addPlugin (/Users/NIlson-mac/Desktop/APPS DUO 
        GOURMET/duo-gourmet-app/platforms/ios/cordova/Api.js:234:10)
             at handleInstall 
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
             at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
             at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
             at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
        Error: Uh oh!
        Cannot find framework "/Users/NIlson-mac/Desktop/APPS DUO 
        GOURMET/duo-gourmet-app/plugins/cordova-plugin-fcm/src/ios/firebase/FirebaseAnalytics.framework" for plugin 
        cordova-plugin-fcm in iOS platform

**Comment by osterland** [comment]
im with cordova-ios@4.4.0 yet - i got errors about the missing Lib, but only in XCode, app is running so far. ( I cant tell in detail if our analytics is getting correct data etc. i doubt it ;) 
So if its urgent, mybe you try 4.4.0
