### ISSUE TITLE
Trouble getting event if app in background or off

### ISSUE THREAD

**Issue by grassick** [fechanique/cordova-plugin-fcm#4]
The code I have to receive the event works great:

`window.FCMPlugin.onNotification(function(data) {  alert(JSON.stringify(data)); }, function() { console.log("fcm success") }, function() { console.log("fcm error")})`

if and only if the app is open. If the app is closed or in background, I get the notification in the status bar, clicking it opens the app, but then onNotification callback never happens for that event. Is there some step I'm missing?

**Comment by fechanique** [comment]
I have checked myself and its working...

Maybe check that you are calling onNotification inside the onDeviceReady event handler

**Comment by grassick** [comment]
I double checked it and I'm calling it directly in `document.addEventListener('deviceready', function() { ...`

It works great when the app is in the foreground. I'm running Android 5.0.1 on an S4 with latest Cordova.

I get the success messages on the console too:

```
I/chromium(32319): [INFO:CONSOLE(5)] "FCMPlugin.js: is created", source: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js (5)
I/chromium(32319): [INFO:CONSOLE(29)] "FCMPlugin Ready OK", source: file:///android_asset/www/plugins/cordova-plugin-fcm/www/FCMPlugin.js (29)
I/chromium(32319): [INFO:CONSOLE(10464)] "Cordova deviceready", source: file:///android_asset/www/js/app.js (10464)
I/chromium(32319): [INFO:CONSOLE(10464)] "fcm success!!", source: file:///android_asset/www/js/app.js (10464)
```

But no callback to the alert function, ever.

**Comment by fechanique** [comment]
Make sure you are including:

"click_action":"FCM_PLUGIN_ACTIVITY",
and at least one data parameter in your payload

**Comment by grassick** [comment]
Worked like a charm. Thanks for the support!

**Comment by bmwertman** [comment]
I implemented the "click_action":"FCM_PLUGIN_ACTIVITY" fix and can redirect to the desired `$state` using UI-router if my app is in the background. But if the app is closed it only opens it to the `$urlRouterProvider.otherwise()` default state. How can I catch the app being opened from cold start by a `click_action`?

**Comment by rakeshbaral92** [comment]
> I implemented the "click_action":"FCM_PLUGIN_ACTIVITY" fix and can redirect to the desired `$state` using UI-router if my app is in the background. But if the app is closed it only opens it to the `$urlRouterProvider.otherwise()` default state. How can I catch the app being opened from cold start by a `click_action`?

Have you got a solution yet. Similar situation I am facing now. When app is closed or killed notification is coming but if I tap the notification then it only opens the first page. But I want to redirect to other page by clicking the notification.
