### ISSUE TITLE
IOS doesn't show notifications when in background or killed.

### ISSUE THREAD

**Issue by AvBrocklehurst** [fechanique/cordova-plugin-fcm#41]
I have made a working chat that allows users to talk between android and ios. On android when the app is in the background or has been killed, the user receives a notification to alert them that a message has been sent. In ios no such notification seems to appear. 

This is the format that I send messages in:

`{
    "notification": {
        "title": "Titlte",
        "body": "body",
        "tag": "tag",
        "click_action": "FCM_PLUGIN_ACTIVITY",
        "icon": "fcm_push_icon",
       "sound":"default",
        "badge": "2",
    },
    "data": {
        "groupID": 77,
        "message": "message",
        "code": 0,
        "sender": "sender",
        "time": "2016-07-11 15:23",
        "signature": ""
    },
    "to": "/topics/77",
    "content_available": true,
    "priority": "high"
}`

Are you able to shed any light on this?

**Comment by AvBrocklehurst** [comment]
It seemed to be caused one provider taking a fair time to update certificates.

**Comment by Pratikick** [comment]
@AvBrocklehurst  were you able to solve this issue?

**Comment by AvBrocklehurst** [comment]
I was @Pratikick , I believe it was an issue with the push notification certificate that apple generated, I regenerated one and it all worked fine.
