### ISSUE TITLE
When notifications arrive in Android, it doesn't vibrate or make sound

### ISSUE THREAD

**Issue by irux** [fechanique/cordova-plugin-fcm#419]
Hallo.

I try to make the Android phone to vibrate. The notification object has already the sound: default option, but it doesn't work.

Have someone an idea ??

Thank you

**Comment by JarikH** [comment]
If you turn up your volume it should make a sound, but for some reason the vibration just isn't coming through.

**Comment by jlvas** [comment]
I'm still having the same issue

**Comment by jlvas** [comment]
actually, I have discovered the issue. I need to enabled the sound from the server side with FCM

**Comment by irux** [comment]
@jlvas do you have it with vibration ??

**Comment by jlvas** [comment]
No vibration, only sound

**Comment by luigi37** [comment]
Hi guys,
my 5 cents. To my knowledge vibration happens when notification sound is muted only. This seems to be by design (but I hope to be wrong).
Luigi

**Comment by PRATHYUSH-DOM** [comment]
You can enable sound in advanced option in FCM Compose message,
Default option of sound is disabled

**Comment by irux** [comment]
Thank you guys. I could fix the problem.
