### ISSUE TITLE
Add the possibility to show notifications when app in foreground

### ISSUE THREAD

**Issue by BugsBunnyBR** [fechanique/cordova-plugin-fcm#42]
I know the default behavior of firebase is not to show the notification when the app is in foreground, but it is like this because firebase is thought to be used in chat/realtime apps and this behavior is a pain in the ass to some other apps.
Just adding the possibility by configuration (saving it in the preferences) would be good enough, it does not need to be the default behavior.

Thanks and sorry for the outburst.

**Comment by fechanique** [comment]
Hi, on iOS it wasn't possible to show stock notifications on foregroud. For that reason there is no such functionality.
I have read that on iOS 10 it will be possible, maybe then I will include your suggestion.

The best solution is to use your own notification alert in your app.

Regards,

**Comment by BugsBunnyBR** [comment]
As far as I know, on iOS when the app is in foreground apps show an alert instead of the notification. To use my own notification I would need to fork this repo and keep it, which is not a very nice thing for me.. Lets wait iOS 10.

Thanks.

**Comment by fechanique** [comment]
Hi, you can capture the notification in your code and then show your alert only using HTML, CSS, JS.
It's quite easy and you'll achieve your requirement.

Regards,
     Felipe.

**Comment by joesleiman** [comment]
how can i check if the the app is in foreground or background? so if it's in foreground i can do alert on my own .
