### ISSUE TITLE
FCMPlugin.onNotification().subscribe does'nt get called On receiving the notification

### ISSUE THREAD

**Issue by naumanahmad17** [fechanique/cordova-plugin-fcm#421]
even notification is received successfully but it does not log any output.

using the following code 
`
this.fcm.onNotification().subscribe(data=>{`
   `   console.log("notification was recevied");`
    `  if(data.wasTapped){`
        `console.log("Received in background");`   
     ` } else {`
      `  console.log("Received in foreground");`   
      `};`
    `})`

what i want to achieve is that when the notification is received and user tap on it a pop up should be open in the app.

for now i just want to log output to see that it works but up till now i am unable to do so.

**Comment by elkadrey** [comment]
any help please ?
