### ISSUE TITLE
Im facing issue after integrate fcm-plugn 

### ISSUE THREAD

**Issue by mrizwan2018** [fechanique/cordova-plugin-fcm#435]
Im facing this issue while i try to emulate build
"The "chunk" argument must be one of type string or Buffer. Received type object" after integrating
this plugin "ionic cordova plugin add cordova-plugin-fcm"
Need help in this regard 
Thanks....!

**Comment by scarface382** [comment]
`Plugin "cordova-plugin-fcm" already installed on android.

Adding cordova-plugin-fcm to package.json
Saved plugin info for "cordova-plugin-fcm" to config.xml
(node:6732) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid dat
a, chunk must be a string or buffer, not object
(node:6732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejec
tions that are not handled will terminate the Node.js process with a non-zero exit code.`

This is the error i get when i try to add this plugin.

I solved it by using an older version of cordova

`npm uninstall -g cordova
npm install -g cordova@7.1.0`

**Comment by mburger81** [comment]
@scarface382 which cordova-android version in package.json do you use?

**Comment by mrizwan2018** [comment]
I found the solutions thanks for everyone for your support!

**Comment by mburger81** [comment]
@mrizwan2018 ok and can you please share your solution with us?

**Comment by mrizwan2018** [comment]
It just platform issue, try to remove and add the platform, also remove and add the plugin.
And its will work fine!

**Comment by mburger81** [comment]
Okay but you are not the only one who has this error. Since cordova-android 7.0.0 there are many many 
 issues on github, which are like this or the the same.

We also tried to remove and add platforms, but always with the same result.

So at the end, after several hours of testing and debugin it seems, the problem is not cordova 8.0.0 but cordova-android 7.0.0.
There are many other plugins which has problems using hight version of cordova-android plugin.

Using 6.4.0 should be fine.

So which cordova-version and which cordova version do you use?

**Comment by mrizwan2018** [comment]
I have 6.3.0 cordova-android and 4.5.4 cordova-ios,

**Comment by scarface382** [comment]
@mburger81 i am using  
`cordova-android: 6.3.0`
`cordova-plugin-fcm: ^2.1.2`
on Windows 7,

downgrading to 7.1 Cordova fixed the issue for me

**Comment by mburger81** [comment]
Okay thanks, on my site global installed `cordova 8.0` does not break the plugin, only `cordova-android >= 7.0.0` does it.

**Comment by JuanCarlosSC** [comment]
I had the same error and could not fix it in any way until I remove the "cordova-plugin-fcm" and install "cordova-plugin-fcm-with-dependecy-updated" and it works perfectly.

**Comment by balwantcom** [comment]
> cordova-plugin-fcm-with-dependecy-updated

Thanks for Answer it's really useful, its working fine.

**Comment by idhowardgj94** [comment]
thanks for saving my day, all of u

**Comment by gonzalezfj** [comment]
ty @JuanCarlosSC
