### ISSUE TITLE
Incompatibility with cordova-android 7.0.0

### ISSUE THREAD

**Issue by mburger81** [fechanique/cordova-plugin-fcm#436]
Hi we are using ionic and cordova to build our android app.

But at the moment there is an incompatibility with `cordova-android 7.0.0` and also it is possible for someone there are problems with `cordova 8.0.0`.

If you google at the moment there are many problems with many plugins because the app structure is changing, for example the res folder is now `./platforms/android/app/src/main/res/` instead of  `./platforms/android/res/`

can someone jump into this error, @fechanique @aparedes

**Comment by ulisesvera** [comment]
Same problem here!

**Comment by mburger81** [comment]
This plugin is not maintained at all and it could be a big problem.

**Comment by mburger81** [comment]
I'm closing this issue in favor of #438 which is more discussed

**Comment by bhumin3i** [comment]
why close i have same issue
