### ISSUE TITLE
How to retrieve the device token?

### ISSUE THREAD

**Issue by Pratikick** [fechanique/cordova-plugin-fcm#45]
I'm new to web development.
Can anyone let me know, how & where do I need to use following code?

FCMPlugin.getToken(
  function(token){
    alert(token);
  },
  function(err){
    console.log('error retrieving token: ' + err);
  }
)

**Comment by fechanique** [comment]
Usually device token is not neccessary. Is better to use topics to reach users.
With that code in your Cordova application you will print the token in an alert.

Regards,

**Comment by Pratikick** [comment]
yes, I want to get the token of individual users. Can you please provide an example where this code snippet works:

FCMPlugin.getToken(
function(token){
alert(token);
},
function(err){
console.log('error retrieving token: ' + err);
}
)
