### ISSUE TITLE
Unable to add sound to notification payload

### ISSUE THREAD

**Issue by paperKeys** [fechanique/cordova-plugin-fcm#458]
I have been unable to add the "sound" field to the notification payload. i receive the following error:

Here is my payload:
{
 "message":
  {  "token":"elhYgHhSs5U:APA91bEuZF0UEanhGgFjWRUofiheJGXEdttIVQl3IklTFfoHepqy5G_au6nme6y5qbmD63L71xw66eyW-3yNrCRUjZ74yovZCEUNbrGrTNfCi9aeGvUIvSIAuAWwiIs4kK4zcdj3u5gP",
   "notification":
    {
	 "title":"Portugal vs. Denmark",
	 "body":"great match!",
	 "sound":"default"
	},
   "data":
    {
	 "Nick":"Mario",
	 "Room":"PortugalVSDenmark"
	}
  }
}

Here is the error:
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"sound\" at 'message.notification': Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.notification",
            "description": "Invalid JSON payload received. Unknown name \"sound\" at 'message.notification': Cannot find field."
          }
        ]
      }
    ]
  }
}

When I send a notification from Firebase with "sound" enabled no sound is played on the device. any suggestions would be very appreciated. thank you!!

**Comment by paperKeys** [comment]
I have found that I am unable to add any additional fields to the notification payload that FCM supports including sound, click action, icon, etc. I can only send a title and body, or a data payload. Any support would be great. Thanks.

**Comment by yayasadiq** [comment]
Hi, I'm having exactly the same problem. If I remove "sound", the message sends successfully but if I include "sound":"default" in my JSON payload, I get the same error

**Comment by paperKeys** [comment]
The issue I was having was two parts.

First, my device had notification sounds silenced for my specific app for some reason (didn't even think of this during testing).

I also changed my payload structure to the one below. On a side note, I was able to remove "sound" entirely from the payload and was still able to get the sound with a notification. However, it doesn't seem to matter if sound is present in the payload as the sound plays either way for me. Here is an example of my payload:

{"message":{"token":"DEVICE_TOKEN",
"data":{
	"title":"Notification title",
	"body":"Notification body",
	"sound":"default",
	"param1":"value1",
	"param2":"value2"
}}}

I also switched my plugin to phonegap-push-plugin thinking this might be part of the problem. I received the same errors when adding to the payload though. Once i changed the structure, however, i stopped getting unknown field errors and the 400. Hope this helps a bit.

**Comment by paperKeys** [comment]
For those interested I found the correct fix for this. The payload must be structured depending on your API version. I was able to have a complete payload and add the sound via the solution provided at the link below. Happy notifying.

https://stackoverflow.com/questions/48690274/firebase-cloud-messaging-sound-error

Solution:
The appearance of message in your JSON indicates you are using the HTTP v1 API. The documentation you linked is for the legacy API.

The HTTP v1 API JSON to send a notification with sound for Android and iOS devices should be:

{
    "message": {
        "token": "your-token-value",
        "notification": {
            "title": "Test",
            "body": "Test message from server"
        },
        "android": {
            "notification": {
                "sound": "default"
            }
        },
        "apns": {
            "payload": {
                "sound": "default"
            }
        }
    }
}

**Comment by Radecom** [comment]
I managed to put icon and custom sound by following this [article](https://medium.com/@ing.ajvillalon/how-to-set-a-custom-icon-for-notifications-on-android-d03a4ad4414e).
I'm working with [Cordova plugin Fcm](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated) in Ionic 4
And so far everything is going well

**Comment by devner007** [comment]
@Radecom I followed the article you shared and placed my sound in the res/raw folder, yet I don't hear the sound on Android.  I placed the notification sound reference in 2 places, one within the **notification** object and another within the **android** object. But none of that seems to work. Within my APK, I have the custom sound in this location: **res > raw > notification.mp3**

Here is the data that I am sending in my notifications (Please ignore the Array thingy as it is PHP output):

```
Array
(
    [to] => djhwYixg2JE:A.....
    [notification] => Array
        (
            [title] => Ticket # 9 - 2:40 PM New message received
            [body] => You received a new message from TESTING on Ticket # 19
            [click_action] => FCM_PLUGIN_ACTIVITY
            [icon] => fcm_push_icon
            [vibrate] => 1
            [sound] => notification
            [forceStart] => 1
            [force-start] => 1
        )

    [data] => Array
        (
            [activity] => test5
            [page] => /support/view-existing-tickets/
            [ticket_id] => 19
        )

    [priority] => high
    [android] => Array
        (
            [notification] => Array
                (
                    [sound] => notification
                )

        )

)
```
Can you please share your solution?

**Comment by Radecom** [comment]
@devner007 I have 2 key questions:
Is the res folder in the same folder as the AndroidManifest.xml file?
Are you trying to hear the notification in background mode? Because the notification does not play in the foreground.
