### ISSUE TITLE
how to subscribe or get token

### ISSUE THREAD

**Issue by Pratikick** [fechanique/cordova-plugin-fcm#46]
I have created a cordova project & installed the cordov-plugin-fcm with some other plugins (like network plugin). 

I am new to web development.

Please let me know how/where to use the below code to get token/subscribe: 
---------
FCMPlugin.getToken(
  function(token){
    alert(token);
  },
  function(err){
    console.log('error retrieving token: ' + err);
  }
)
------------
FCMPlugin.subscribeToTopic('topicExample');

**Comment by fechanique** [comment]
Hi,

If you need premium support, you can purchase a starter application for you
with all the things configured and also with all the support you need in
order to have your application ready to receive push notifications.

Pay with PayPal
<https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=32VKGMKKV75JE&user_id=PK5789>
​
Regards,
    Felipe.

2016-07-22 15:30 GMT+02:00 Pratikick <notifications@github.com>:

**Comment by aparedes** [comment]
you can get the token after the device is ready and cordova is loaded. 

https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready

```javascript
document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {
    // Now safe to use device APIs
}
```

**Comment by Pratikick** [comment]
thanks. it works
