### ISSUE TITLE
While instllation: (node:21564) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1):

### ISSUE THREAD

**Issue by michalsindler** [fechanique/cordova-plugin-fcm#469]
I'm trying install this plugin into Ionic project.

$ ionic cordova plugin add cordova-plugin-fcm
Installing "cordova-plugin-fcm" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app

		Cordova FCM plugin v2.1.2 installed
		For more details visit https://github.com/fechanique/cordova-plugin-fcm

Adding cordova-plugin-fcm to package.json
Saved plugin info for "cordova-plugin-fcm" to config.xml
(node:21564) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid data, chunk must be a string or buffer, not object

Ionic info:
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v6.11.4
    npm        : 3.10.10
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

Does anybody knows what is wrong?

**Comment by michalsindler** [comment]
Ok, it looks like there is some problem with json/plist files for android/ios platform.
When I removed both platforms and install plugin again, it went ok.

Downgrade to cordova 6.5.0 fixed this issue.

**Comment by gireeshscs** [comment]
anybody help to reolve the cordova error
(node:6842) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1):  while adding FCM plugin.
