### ISSUE TITLE
Only show background notifications based on content of message?

### ISSUE THREAD

**Issue by nikmartin** [fechanique/cordova-plugin-fcm#47]
I have the need to allow users to enable and disable background messages based on content of an fcm notification. The payload of the notifications has data that a user can choose to ignore notifications on. Is it possible to do this, or will I have to implement this using topics or some other method?

**Comment by aparedes** [comment]
It can only be done with topics or send to specific users.

**Comment by nikmartin** [comment]
Yes, I have determined that the app will need to subscribe to the specific topics it wants to be notified of. The issue there is the amount of time it takes to start a topic is variable, and much longer than I'd expect it to be.

**Comment by aparedes** [comment]
Actually creating the topic is quite fast, but it takes time to show in the console. Or at least that is what I have experienced.   
  
  
  

  
  
>

**Comment by nikmartin** [comment]
Ah, OK, I was worried that the actual topic creation by subscribing via the client was also soem sort of batched process. Good to know.
