### ISSUE TITLE
Invalid data, chunk must be a string or buffer, not object

### ISSUE THREAD

**Issue by UrbanSwati** [fechanique/cordova-plugin-fcm#481]
Hey, after following [ionic fcm](https://ionicframework.com/docs/native/fcm/) instrution on installing the plugin then I added the Android platform using `ionic Cordova platform add android` I get an exception: 
```
(node:5644) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid data, chunk must be a string or buffer, not object 
``` 
when I try to build android app

**Comment by GilTads** [comment]
Same problem here.

**Comment by fabiusss** [comment]
+1
`Executing script found in plugin cordova-plugin-fcm for hook "after_prepare": plugins\cordova-plugin-fcm\scripts\fcm_config_files_process.js
(node:23484) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid data, chunk must be a string or buffer, not object`

**Comment by ghost** [comment]
Same issue.

**Comment by cipriancirstea** [comment]
Same here when building iOS or Android.

`(node:58497) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer
    at validChunk (_stream_writable.js:253:10)
    at Socket.Writable.write (_stream_writable.js:288:21)
    at Socket.stream.write (/usr/local/lib/node_modules/cordova/node_modules/ansi/lib/newlines.js:36:21)
    at Object.<anonymous> (/Users/xxx/Documents/xxx/plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js:80:24)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
(node:58497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58497) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by GilTads** [comment]
After many attempts, unfortunately I had to migrate to https://github.com/guyromb/cordova-plugin-fcm-plus. Apparently it solved my problem.

**Comment by cipriancirstea** [comment]
What's the difference between plus and this one?

**Comment by Alacon** [comment]
I get the same issue with [cordova-plugin-fcm-plus](https://github.com/guyromb/cordova-plugin-fcm-plus) @GilTads 

Any other suggestions?

**Comment by valmirphp** [comment]
Consegui resolver o problema,  alterando o arquivo: `plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js`

```js 
// change
var strings = fs.readFileSync("platforms/android/res/values/strings.xml").toString();
// to
var strings = fs.readFileSync("platforms/android/app/src/main/res/values/strings.xml").toString();

// AND

//change
fs.writeFileSync("platforms/android/res/values/strings.xml", strings);

//to
fs.writeFileSync("platforms/android/app/src/main/res/values/strings.xml", strings);
```

copie o arquivo `google-services.json` para os seguintes diretórios:
- platforms/android/google-services.json
- platforms/android/app/google-services.json




Obs: 
cordova (Cordova CLI) : 8.0.0 
Cordova Platforms  : android 7.0.0

**Comment by UrbanSwati** [comment]
@valmirphp Thanks! That worked!

**Comment by borjalo** [comment]
@valmirphp It worked, but now, notifications don't appear

**Comment by valmirphp** [comment]
@borjalo Faça o listerner dos evento dentro do modulo componentes

https://github.com/ionic-team/ionic2-starter-tabs/blob/master/src/app/app.component.ts#L19
```ts
 platform.ready().then(() => {
 //.... 
    this.fcm.onNotification().subscribe(data => { 
    .....
```

deixa a linha a baixo comentada
```ts
// this.fcm.unsubscribeFromTopic('marketing');
```

**Comment by tousif03raza** [comment]
@valmirphp  Thanks, it worked!

**Comment by mickadam** [comment]
Apparently fcm is not compliant with cordova android 7.0
for me I change the version to 6.4 and this work greet:

```
cordova platform rm android
cordova platform add android@6.4.0
```

**Comment by SilvestreBalboa** [comment]
Thank mickadam, your solution resolved my problem

**Comment by cipriancirstea** [comment]
Worked for me without having to change android version. Just followed @valmirphp s instructions.

**Comment by danilocecilia** [comment]
@valmirphp 's solution worked for me! Tks

**Comment by ale2k** [comment]
@valmirphp 's solution worked for me as well!
thanks a lot!

**Comment by esfand55** [comment]
@valmirphp 's solution worked for me too. Thanks

**Comment by VLazzarova** [comment]
I also get the same after i runf cordova add platform and when i try to build the project. Tried the solution of @valmirphp  but  I can't fin the google-services.json

**Comment by piyushpatil027** [comment]
@valmirphp  Thanks it worked.

**Comment by arjabbar** [comment]
So should this be a pull request? Or is there one already out?

**Comment by piyushpatil027** [comment]
No, you have to change that setting in platform folder.

**Comment by awaisatiq** [comment]
It is a issue with fcm_config_files_process.js file placed in [your project]/plugins/scripts

Change this code 

        fs.writeFileSync("platforms/android/google-services.json", contents);

        var json = JSON.parse(contents);
        var strings = fs.readFileSync("platforms/android/res/values/strings.xml").toString();

        // strip non-default value
        strings = strings.replace(new RegExp('<string name="google_app_id">([^\@<]+?)</string>', "i"), '')

        // strip non-default value
        strings = strings.replace(new RegExp('<string name="google_api_key">([^\@<]+?)</string>', "i"), '')

        // strip empty lines
        strings = strings.replace(new RegExp('(\r\n|\n|\r)[ \t]*(\r\n|\n|\r)', "gm"), '$1')

        // replace the default value
        strings = strings.replace(new RegExp('<string name="google_app_id">([^<]+?)</string>', "i"), '<string name="google_app_id">' + json.client[0].client_info.mobilesdk_app_id + '</string>')

        // replace the default value
        strings = strings.replace(new RegExp('<string name="google_api_key">([^<]+?)</string>', "i"), '<string name="google_api_key">' + json.client[0].api_key[0].current_key + '</string>')

        fs.writeFileSync("platforms/android/res/values/strings.xml", strings);

to this

        fs.writeFileSync("platforms/android/google-services.json", contents);
        fs.writeFileSync("platforms/android/app/google-services.json", contents);

        // var json = JSON.parse(contents);
        // var strings = fs.readFileSync("platforms/android/res/values/strings.xml").toString();

        // // strip non-default value
        // strings = strings.replace(new RegExp('<string name="google_app_id">([^\@<]+?)</string>', "i"), '')

        // // strip non-default value
        // strings = strings.replace(new RegExp('<string name="google_api_key">([^\@<]+?)</string>', "i"), '')

        // // strip empty lines
        // strings = strings.replace(new RegExp('(\r\n|\n|\r)[ \t]*(\r\n|\n|\r)', "gm"), '$1')

        // // replace the default value
        // strings = strings.replace(new RegExp('<string name="google_app_id">([^<]+?)</string>', "i"), '<string name="google_app_id">' + json.client[0].client_info.mobilesdk_app_id + '</string>')

        // // replace the default value
        // strings = strings.replace(new RegExp('<string name="google_api_key">([^<]+?)</string>', "i"), '<string name="google_api_key">' + json.client[0].api_key[0].current_key + '</string>')

        // fs.writeFileSync("platforms/android/res/values/strings.xml", strings);

Old code does not copy google-services.json to app directory in Android Platform.

**Comment by mismith** [comment]
As @awaisatiq discovered, it also fails to open the `strings.xml` file, giving the following error:
```
{ Error: ENOENT: no such file or directory, open 'platforms/android/res/values/strings.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (<app>/plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js:62:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'platforms/android/res/values/strings.xml' }
```

**Comment by snsfrisco** [comment]
Thanks this worked for me

**Comment by JuanCarlosSC** [comment]
I had the same error and could not fix it in any way until I remove the "cordova-plugin-fcm" and install "cordova-plugin-fcm-with-dependecy-updated" and it works perfectly.

**Comment by Pamblam** [comment]
where the heck is the maintainer. those of us who don't want to have to version control the entire plugins folder are not going to be able to use this fix. migrating over to [cordova-plugin-fcm-with-dependecy-updated](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated).

**Comment by yphanikumar2869** [comment]
Hi,
I made the above all changes but it doesnot work for me .
The solution for the version conflict between FCM plugin and google maps or google services plugin is as follows..
I resolved the issue just by adding the below lines in platform>android>cordova-plugin-fcm>app-FCMPlugin.gradle

ext.postBuildExtras = {
    apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
}

**Comment by rodrigoespinozadev** [comment]
> Consegui resolver o problema, alterando o arquivo: `plugins/cordova-plugin-fcm/scripts/fcm_config_files_process.js`
> 
> ```js
> // change
> var strings = fs.readFileSync("platforms/android/res/values/strings.xml").toString();
> // to
> var strings = fs.readFileSync("platforms/android/app/src/main/res/values/strings.xml").toString();
> 
> // AND
> 
> //change
> fs.writeFileSync("platforms/android/res/values/strings.xml", strings);
> 
> //to
> fs.writeFileSync("platforms/android/app/src/main/res/values/strings.xml", strings);
> ```
> 
> copie o arquivo `google-services.json` para os seguintes diretórios:
> 
> * platforms/android/google-services.json
> * platforms/android/app/google-services.json
> 
> Obs:
> cordova (Cordova CLI) : 8.0.0
> Cordova Platforms : android 7.0.0

Thanks Amigo!
