### ISSUE TITLE
Distinguish between notification tray and foreground app

### ISSUE THREAD

**Issue by grassick** [fechanique/cordova-plugin-fcm#5]
A common use case of FCM is to notify the user that a new email, ticket, etc. needs their attention. If they are outside of the app, tapping on the notification should take them directly to the item. But if they are in the app, it would be rather jarring to dump them directly from what they are doing to the new email, and would be better to show them a toast that they could click on if they want to go.

To do this, I need to know whether the message was received while the app was in the foreground, or if it was triggered from tapping the notification in the notification tray. Do you happen to know if there a way to get this information out of FCM?

**Comment by fechanique** [comment]
This will be included in the tomorrow release

**Comment by grassick** [comment]
Fantastic! Thanks!
