### ISSUE TITLE
Icon customisation

### ISSUE THREAD

**Issue by 4j1th** [fechanique/cordova-plugin-fcm#508]
I have some doubt about the icon placing, I searched in google and I apply many solutions but none of them worked.

I generated icons using http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=0&source.space.pad=0&name=fcm_push_icon
used their default for testing but still not working

In README it only says place `fcm_push_icon.png` in `res` dir so I place [cordova_project_dir]/res and place the `drawable-XXXX` in the same dir. I don't know what I did wrong.

Cordova 8.0.0

**Comment by 4j1th** [comment]
copy icon in `[cordova_project_dir]/platforms/android/app/src/main/res/`

```
drawable-hdpi
drawable-land-hdpi
drawable-land-ldpi
drawable-land-mdpi
drawable-land-xhdpi
drawable-land-xxhdpi
drawable-land-xxxhdpi
drawable-ldpi
drawable-mdpi
drawable-port-hdpi
drawable-port-ldpi
drawable-port-mdpi
drawable-port-xhdpi
drawable-port-xxhdpi
drawable-port-xxxhdpi
drawable-xhdpi
drawable-xxhdpi
drawable-xxxhdpi
```

with different sizes according to the dir in the name fcm_push_icon.png

generate a png transparent file (I did it in 1024*1024px) for your white icon which will be displayed in the status bar upload it in the [Android Notification Icon Generator](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=0&source.space.pad=0&name=fcm_push_icon)

**Comment by devner007** [comment]
I am using the [FCM plugin](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated) and here is what worked for me (September 2019):
1.  In **config.xml** (yourapp/config.xml)
Add the following to the <widget id=""...> tag at the end
`xmlns:android="http://schemas.android.com/apk/res/android"`

It should look something like this now:

`<widget id="com.mydomain.app" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:android="http://schemas.android.com/apk/res/android">`

Or simply, copy the above line, replace the value of widget id, with your own.

2. In the same **config.xml** file:
Just before the </platform> tag corresponding to <platform name="android">, add this:

```
<config-file parent="/manifest/application/" target="app/src/main/AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/fcm_push_icon" />
</config-file>
```
3. Visit the following link:
[Notification Icon Generator](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=1&source.space.pad=0&name=fcm_push_icon)

Upload a **White version (single color) of your logo on a Transparent background**. If you upload a colored version, you will get a dark gray icon, which would look nasty. If you don't have a white version of your logo, get it designed. Leave the rest of the settings as they are. For the Name textbox value, enter: **fcm_push_icon**. Then click on the Blue colored round shaped button to download the zip file. 

4. Unzip the zip file that you just downloaded it the above step and extract its contents to a folder. You will notice that it contains a **res** folder. If you open this folder, it will contain other folders with the following names:

- drawable-hdpi
- drawable-mdpi
- drawable-xhdpi
- drawable-xxhdpi
- drawable-xxxhdpi

Each of those folders will contain a PNG icon by the name "fcm_push_icon.png". The only difference between the icons in those different folders is their size. 

5. Open the following file path in your app (If it doesn't exist, create it as shown below):

`yourApp/platforms/android/app/src/main/res`

Simply copy all the 5 folders listed in in the point 4 above, to the location shown just above i.e. into the **res** folder i.e. into `yourApp/platforms/android/app/src/main/res`

That's it! Now just build your app. Whenever you receive a notification, you will see your app icon in the notifications (at least on Android).

**_If anyone has figured out how to make colored icons appear in the Android notifications, please share your solution._**
