### ISSUE TITLE
How to control the Status Bar Notification?

### ISSUE THREAD

**Issue by rcubarocha** [fechanique/cordova-plugin-fcm#51]
I'm wondering how one can get control on the notification that appears on the Status Bar when the push arrives while the application is not on the foreground.

I would like to selectively display a status bar notification or modify an existing one, but I can't see where this is handled. At least on Android.

I see [here](https://github.com/fechanique/cordova-plugin-fcm/blob/master/src/android/MyFirebaseMessagingService.java#L53) that the actual call to sendNotification is commented out and upon debugging on Android, that function doesn't seem called at all.

Where is the status bar notification for the push built?

**Comment by fechanique** [comment]
Hi, when application is in background, is the system itself which controls the notificationrs. On Android you can override them, but not on iOS. Since I want the same behaviour for all platforms, I haven't implemented such functionality.
