### ISSUE TITLE
Notification tap does not call FCMPlugin.onNotification

### ISSUE THREAD

**Issue by ullfindsmit** [fechanique/cordova-plugin-fcm#528]
When the app is closed or in the background, tapping the message opens the app but does not call the function.

Send a push notification to a single device or topic.

1.a Application is in foreground:
The notification data is received in the JavaScript callback without notification bar message (this is the normal behaviour of mobile push notifications).
1.b Application is in background or closed:
The device displays the notification message in the device notification bar.
If the user taps the notification, the application comes to foreground and the notification data is received in the JavaScript callback.
If the user does not tap the notification but opens the applicacion, nothing happens until the notification is tapped.

**Comment by ullfindsmit** [comment]
My code is as shown below.

        FCMPlugin.onNotification(
            function (data) {
                alert("onNotification" + data);
                if (data.wasTapped) {
                    alert("Tapped");
                    appendMessage(data);
                    //Notification was received on device tray and tapped by the user.
                    alert(JSON.stringify(data));
                } else {
                    alert("Got");
                    appendMessage(data);
                    //Notification was received in foreground. Maybe the user needs to be notified.
                    alert(JSON.stringify(data));
                }
            },
            function (msg){
                alert("msg" + msg);
            },
            function (err){
                alert("err" + err);
            }
        );

**Comment by salime45** [comment]
Hi

How you send the notification?

What is the payload of notification?

**Comment by orehush** [comment]
Hello
@ullfindsmit you should add this param "click_action":"FCM_PLUGIN_ACTIVITY" to notification payload.
See [here](https://github.com/fechanique/cordova-plugin-fcm#send-notification-payload-example-rest-api)

**Comment by ullfindsmit** [comment]
"click_action":"FCM_PLUGIN_ACTIVITY"

did the trick

**Comment by dexterprabhakar** [comment]
hello guys, i have same issue. i added the click action. this has helped in sending the message till FCMPlugin.java file where it is able to identified data.tapped action. but still onNotification(data) js callback is not getting called. 

i need to perform action on the data recieved in notification data. any help will be appriciated. 
Thanks

**Comment by asiermusa** [comment]
Hi,

Here the solution for me. **'click_action'** with the value **FCM_PLUGIN_ACTIVITY** must be present in the notification object:

```
{
  "notification":{
    "title":"Notification title",  //Any value
    "body":"Notification body",  //Any value
    "sound":"default", //If you want notification sound
    "click_action":"FCM_PLUGIN_ACTIVITY",  //Must be present for Android
  }
```
