### ISSUE TITLE
Plugin Conflict?

### ISSUE THREAD

**Issue by SteveFulton95** [fechanique/cordova-plugin-fcm#53]
When I have both cordova-plugin-fcm and cordova-plugin-request-location-accuracy plugins installed my build fails. Here is the output:

Found com.google.android.gms:play-services-location:+, but version 9.2.0 is needed for the google-services plugin.
:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.

When I have one or the other installed the build is successful.

**Comment by sergtop** [comment]
had the same issue with cordova-plugin-background-geolocation, I`ve solved it by changing "+" in 
com.google.android.gms:play-services-location:+ - to com.google.android.gms:play-services-location:9.2.0 in all places. Seems it is not a FCM plugin issue

**Comment by SteveFulton95** [comment]
Yeah I fixed it myself too. I hate dealing with issues like that. I'll close this.

**Comment by fechanique** [comment]
do you have a solution so I can help others with this?

**Comment by SteveFulton95** [comment]
First, make sure to remove the platforms from your project.
I changed the '+' to '9.2.0' within plugin.xml. (plugins/somepluginconflict/plugin.xml)

com.google.android.gms:play-services-location:+
-->
com.google.android.gms:play-services-location:9.2.0

After that, I then added the platform I was working with. This solved my issue.

**Comment by rabbounicha** [comment]
Hello,

I did as SteveFulton95 said. The conflict between cordova fcm plugin and cordova geolocalisation plugin is solved.

But now i have a new error : 

:transformClassesWithDexForDebug
 FAILED

BUILD FAILED

Total time: 32.749 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/api/zza;

Please anyone help me.

**Comment by PointmanDev** [comment]
Having the same issue. Did you ever figure this out?

**Comment by rabbounicha** [comment]
@PointmanDev  after running "ionic run android --device" or "ionic build android", you need to change all + by a specific version in platform/android/project.properties expect com.android.support:support-v4:+ . In my case, i replaced all + by 9.0.0 and it worked.
