### ISSUE TITLE
Plugin not  working on Android Oreo

### ISSUE THREAD

**Issue by imrankhaki** [fechanique/cordova-plugin-fcm#533]
I am working on ionic app with   cordova version 8.0.0 and ionic CLI 3.20.0. The plugin is working on Android with version less than 8 but when i test the same on Android 8, it is not receiving notifications. 
Any help!

**Comment by imrankhaki** [comment]
I resolved the problem by adding few lines in the file MyFirebaseMessagingService.java at ~\plugins\cordova-plugin-fcm\src\android.
Replace the code with:

package com.gae.scaffolder.plugin;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.media.RingtoneManager;
import android.net.Uri;
import android.support.v4.app.NotificationCompat;
import android.app.Notification;
import android.content.ContextWrapper;
import android.graphics.Color;
import android.util.Log;
import java.util.Map;
import java.util.HashMap;

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;

/**
 * Created by Felipe Echanique on 08/06/2016.
 */
public class MyFirebaseMessagingService extends FirebaseMessagingService {

    private static final String TAG = "FCMPlugin";
	private String getStringResource(String name) {
        return this.getString(
                this.getResources().getIdentifier(
                        name, "string", this.getPackageName()
                )
        );
    }
	
	public class NotificationUtils extends ContextWrapper {
 
		private NotificationManager mManager;
		public static final String ANDROID_CHANNEL_ID = "com.ionicframework.mynet540360.ANDROID";
		public static final String ANDROID_CHANNEL_NAME = "Miscellaneous"; 
		public NotificationUtils(Context base) {
			super(base);
			createChannels();
		}
	 
		public void createChannels() {
	 
			// create android channel
			NotificationChannel androidChannel = new NotificationChannel(ANDROID_CHANNEL_ID,
					ANDROID_CHANNEL_NAME, NotificationManager.IMPORTANCE_DEFAULT);
			// Sets whether notifications posted to this channel should display notification lights
			androidChannel.enableLights(true);
			// Sets whether notification posted to this channel should vibrate.
			androidChannel.enableVibration(true);
			// Sets the notification light color for notifications posted to this channel
			androidChannel.setLightColor(Color.GREEN);
			// Sets whether notifications posted to this channel appear on the lockscreen or not
			androidChannel.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);
	 
			getManager().createNotificationChannel(androidChannel);
	 
			
		}
	 
		private NotificationManager getManager() {
			if (mManager == null) {
				mManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
			}
			return mManager;
		}
	}

    /**
     * Called when message is received.
     *
     * @param remoteMessage Object representing the message received from Firebase Cloud Messaging.
     */
    // [START receive_message]
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        // TODO(developer): Handle FCM messages here.
        // If the application is in the foreground handle both data and notification messages here.
        // Also if you intend on generating your own notifications as a result of a received FCM
        // message, here is where that should be initiated. See sendNotification method below.
        Log.d(TAG, "==> MyFirebaseMessagingService onMessageReceived");
		
		if( remoteMessage.getNotification() != null){
			Log.d(TAG, "\tNotification Title: " + remoteMessage.getNotification().getTitle());
			Log.d(TAG, "\tNotification Message: " + remoteMessage.getNotification().getBody());
		}
		
		Map<String, Object> data = new HashMap<String, Object>();
		data.put("wasTapped", false);
		for (String key : remoteMessage.getData().keySet()) {
                Object value = remoteMessage.getData().get(key);
                Log.d(TAG, "\tKey: " + key + " Value: " + value);
				data.put(key, value);
        }
		
		Log.d(TAG, "\tNotification Data: " + data.toString());
        FCMPlugin.sendPushPayload( data );
        //sendNotification(remoteMessage.getNotification().getTitle(), remoteMessage.getNotification().getBody(), remoteMessage.getData());
    }
    // [END receive_message]

    /**
     * Create and show a simple notification containing the received FCM message.
     *
     * @param messageBody FCM message body received.
     */
    private void sendNotification(String title, String messageBody, Map<String, Object> data) {
        Intent intent = new Intent(this, FCMPluginActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
		for (String key : data.keySet()) {
			intent.putExtra(key, data.get(key).toString());
		}
        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent,
                PendingIntent.FLAG_ONE_SHOT);
		String channelId = this.getStringResource("default_notification_channel_id");
        String channelName = this.getStringResource("default_notification_channel_name");
        Uri defaultSoundUri= RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId)
                .setSmallIcon(getApplicationInfo().icon)
                .setContentTitle(title)
                .setContentText(messageBody)
                .setAutoCancel(true)
                .setSound(defaultSoundUri)
                .setContentIntent(pendingIntent);

        NotificationManager notificationManager =
                (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
			NotificationChannel channel = new NotificationChannel(channelId, channelName, NotificationManager.IMPORTANCE_HIGH);
			notificationManager.createNotificationChannel(channel);
		}
        notificationManager.notify(0 /* ID of notification */, notificationBuilder.build());
    }
}

**Comment by imrankhaki** [comment]
I resolved the problem by adding few lines in the file MyFirebaseMessagingService.java at ~\plugins\cordova-plugin-fcm\src\android.
Replace the code with:

`package com.gae.scaffolder.plugin;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.media.RingtoneManager;
import android.net.Uri;
import android.support.v4.app.NotificationCompat;
import android.app.Notification;
import android.content.ContextWrapper;
import android.graphics.Color;
import android.util.Log;
import java.util.Map;
import java.util.HashMap;

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;

/**
 * Created by Felipe Echanique on 08/06/2016.
 */
public class MyFirebaseMessagingService extends FirebaseMessagingService {

    private static final String TAG = "FCMPlugin";
	private String getStringResource(String name) {
        return this.getString(
                this.getResources().getIdentifier(
                        name, "string", this.getPackageName()
                )
        );
    }
	
	public class NotificationUtils extends ContextWrapper {
 
		private NotificationManager mManager;
		public static final String ANDROID_CHANNEL_ID = "com.ionicframework.mynet540360.ANDROID";
		public static final String ANDROID_CHANNEL_NAME = "Miscellaneous"; 
		public NotificationUtils(Context base) {
			super(base);
			createChannels();
		}
	 
		public void createChannels() {
	 
			// create android channel
			NotificationChannel androidChannel = new NotificationChannel(ANDROID_CHANNEL_ID,
					ANDROID_CHANNEL_NAME, NotificationManager.IMPORTANCE_DEFAULT);
			// Sets whether notifications posted to this channel should display notification lights
			androidChannel.enableLights(true);
			// Sets whether notification posted to this channel should vibrate.
			androidChannel.enableVibration(true);
			// Sets the notification light color for notifications posted to this channel
			androidChannel.setLightColor(Color.GREEN);
			// Sets whether notifications posted to this channel appear on the lockscreen or not
			androidChannel.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);
	 
			getManager().createNotificationChannel(androidChannel);
	 
			
		}
	 
		private NotificationManager getManager() {
			if (mManager == null) {
				mManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
			}
			return mManager;
		}
	}

    /**
     * Called when message is received.
     *
     * @param remoteMessage Object representing the message received from Firebase Cloud Messaging.
     */
    // [START receive_message]
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        // TODO(developer): Handle FCM messages here.
        // If the application is in the foreground handle both data and notification messages here.
        // Also if you intend on generating your own notifications as a result of a received FCM
        // message, here is where that should be initiated. See sendNotification method below.
        Log.d(TAG, "==> MyFirebaseMessagingService onMessageReceived");
		
		if( remoteMessage.getNotification() != null){
			Log.d(TAG, "\tNotification Title: " + remoteMessage.getNotification().getTitle());
			Log.d(TAG, "\tNotification Message: " + remoteMessage.getNotification().getBody());
		}
		
		Map<String, Object> data = new HashMap<String, Object>();
		data.put("wasTapped", false);
		for (String key : remoteMessage.getData().keySet()) {
                Object value = remoteMessage.getData().get(key);
                Log.d(TAG, "\tKey: " + key + " Value: " + value);
				data.put(key, value);
        }
		
		Log.d(TAG, "\tNotification Data: " + data.toString());
        FCMPlugin.sendPushPayload( data );
        //sendNotification(remoteMessage.getNotification().getTitle(), remoteMessage.getNotification().getBody(), remoteMessage.getData());
    }
    // [END receive_message]

    /**
     * Create and show a simple notification containing the received FCM message.
     *
     * @param messageBody FCM message body received.
     */
    private void sendNotification(String title, String messageBody, Map<String, Object> data) {
        Intent intent = new Intent(this, FCMPluginActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
		for (String key : data.keySet()) {
			intent.putExtra(key, data.get(key).toString());
		}
        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent,
                PendingIntent.FLAG_ONE_SHOT);
		String channelId = this.getStringResource("default_notification_channel_id");
        String channelName = this.getStringResource("default_notification_channel_name");
        Uri defaultSoundUri= RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId)
                .setSmallIcon(getApplicationInfo().icon)
                .setContentTitle(title)
                .setContentText(messageBody)
                .setAutoCancel(true)
                .setSound(defaultSoundUri)
                .setContentIntent(pendingIntent);

        NotificationManager notificationManager =
                (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
			NotificationChannel channel = new NotificationChannel(channelId, channelName, NotificationManager.IMPORTANCE_HIGH);
			notificationManager.createNotificationChannel(channel);
		}
        notificationManager.notify(0 /* ID of notification */, notificationBuilder.build());
    }
}
`

**Comment by imrankhaki** [comment]
I fixed the problem by adding few lines in file MyFirebaseMessagingService.java at ~/plugins\cordova-plugin-fcm\src\android. You can replace the code of the file with the below: 

package com.gae.scaffolder.plugin;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.ContextWrapper;
import android.graphics.Color;
import android.content.Intent;
import android.media.RingtoneManager;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.NotificationCompat;
import android.util.Log;
import android.app.Notification;
import java.util.Map;
import java.util.HashMap;
import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
/**
 * Created by Felipe Echanique on 08/06/2016.
 */
public class MyFirebaseMessagingService extends FirebaseMessagingService 
{
        private static final String TAG = "FCMPlugin";
	 private String getStringResource(String name) {
            return this.getString(
                this.getResources().getIdentifier(name, "string", this.getPackageName())
            );
        }
	public class NotificationUtils extends ContextWrapper {
		private NotificationManager mManager;
		public static final String ANDROID_CHANNEL_ID = 
                "com.ionicframework.mynet540360.ANDROID";
		public static final String ANDROID_CHANNEL_NAME = "Miscellaneous";
		public NotificationUtils(Context base) {
			super(base);
			createChannels();
		}
		public void createChannels() {
			// create android channel
			NotificationChannel androidChannel = new NotificationChannel(ANDROID_CHANNEL_ID, 
                        ANDROID_CHANNEL_NAME, NotificationManager.IMPORTANCE_DEFAULT);
			// Sets whether notifications posted to this channel should display notification lights
			androidChannel.enableLights(true);
			// Sets whether notification posted to this channel should vibrate.
			androidChannel.enableVibration(true);
			// Sets the notification light color for notifications posted to this channel
			androidChannel.setLightColor(Color.GREEN);
			// Sets whether notifications posted to this channel appear on the lockscreen or not
			androidChannel.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);
			getManager().createNotificationChannel(androidChannel);
		}
		private NotificationManager getManager() {
			if (mManager == null) {
				mManager = (NotificationManager) 
                                getSystemService(Context.NOTIFICATION_SERVICE);
			}
			return mManager;
		}
	}
    /**
     * Called when message is received.
     *
     * @param remoteMessage Object representing the message received from Firebase Cloud 
        Messaging.
     */
    // [START receive_message]
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        // TODO(developer): Handle FCM messages here.
        // If the application is in the foreground handle both data and notification messages here.
        // Also if you intend on generating your own notifications as a result of a received FCM
        // message, here is where that should be initiated. See sendNotification method below.
        Log.d(TAG, "==> MyFirebaseMessagingService onMessageReceived");
		if( remoteMessage.getNotification() != null){
			Log.d(TAG, "\tNotification Title: " + remoteMessage.getNotification().getTitle());
			Log.d(TAG, "\tNotification Message: " + remoteMessage.getNotification().getBody());
		}
		Map<String, Object> data = new HashMap<String, Object>();
		data.put("wasTapped", false);
		for (String key : remoteMessage.getData().keySet()) {
                Object value = remoteMessage.getData().get(key);
                Log.d(TAG, "\tKey: " + key + " Value: " + value);
		data.put(key, value);
        }
	Log.d(TAG, "\tNotification Data: " + data.toString());
        FCMPlugin.sendPushPayload( data );  //sendNotification(remoteMessage.getNotification().getTitle(),remoteMessage.getNotification().getBody(), remoteMessage.getData());
    }
    // [END receive_message]
    /**
     * Create and show a simple notification containing the received FCM message.
     *
     * @param messageBody FCM message body received.
     */
    private void sendNotification(String title, String messageBody, Map<String, Object> data) {
        Intent intent = new Intent(this, FCMPluginActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
		for (String key : data.keySet()) {
			intent.putExtra(key, data.get(key).toString());
		}
        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent, 
        PendingIntent.FLAG_ONE_SHOT);
	String channelId = this.getStringResource("default_notification_channel_id");
        String channelName = this.getStringResource("default_notification_channel_name");
        Uri defaultSoundUri= RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId)
                .setSmallIcon(getApplicationInfo().icon)
                .setContentTitle(title)
                .setContentText(messageBody)
                .setAutoCancel(true)
                .setSound(defaultSoundUri)
                .setContentIntent(pendingIntent);
        NotificationManager notificationManager = (NotificationManager) 
        getSystemService(Context.NOTIFICATION_SERVICE);
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
			NotificationChannel channel = new NotificationChannel(channelId, channelName, 
                        NotificationManager,IMPORTANCE_HIGH);
			notificationManager.createNotificationChannel(channel);
		}
        notificationManager.notify(0 /* ID of notification */, notificationBuilder.build());
    }
}

**Comment by akash-pal** [comment]
@imrankhaki  please raise a pull request

**Comment by harithFED** [comment]
what is the IMPORTANCE_HIGH value? ddnt see any declaration

**Comment by falkop** [comment]
> what is the IMPORTANCE_HIGH value? ddnt see any declaration

https://developer.android.com/training/notify-user/channels see section "Set the importance level"

**Comment by saberprashant** [comment]
HI @imrankhaki , the solution you provided isn't working. It ran into many compilation errors.

**Comment by coolvasanth** [comment]
I'm also facing same problem, anybody else have found solution for this ?
