### ISSUE TITLE
Android Custom Push Sounds not work

### ISSUE THREAD

**Issue by unl0ck** [fechanique/cordova-plugin-fcm#538]
Has anyone the issue with Cordova 8.0.0 and Cordova-android 7.0.0
that the custom push sounds will not played?
I set the path
but nothing work.

**Comment by coyu1314** [comment]
I have the same issue and found that custom sound doesn't work on android oreo 8.0+ out of the box. you need to create a channel in the app and then pass the channel id in your notification payload. However, I can't find anywhere in this plugin to create a channel. 
If anyone know how to create  a channel in this plugin. Please share. I am still looking for a solution on this issue.

**Comment by ppetree** [comment]
Did anyone ever resolve this?

**Comment by cabrerabastian** [comment]
help with this please
