### ISSUE TITLE
Any idea why push notifications works only in background mode on iOS ?

### ISSUE THREAD

**Issue by kirill-kostenetskyi** [fechanique/cordova-plugin-fcm#539]
onNotification trigger won't works once application in foreground mode. In background mode I am able to see push notifications. What can be a problem ?
All fork fine with Android.
Here is my json:
```
{
        "notification": {
            "title": title,
            "body": messagebody,
            "sound": "default",
            "click_action": "FCM_PLUGIN_ACTIVITY",
            "icon": "fcm_push_icon"
        },
        "data": {
            "param1": "value1",
            "param2": "value2"
        },
        "to": to,
        "priority": "high",
        "restricted_package_name": "com.myapp"
    }
```

**Comment by accttech** [comment]
I am having the same problem, but on Android instead of IOS. Did you figure it out?

**Comment by kirill-kostenetskyi** [comment]
@accttech no, I spent a few days without success

**Comment by kirill-kostenetskyi** [comment]
Finally I've found a reason. Another plugin `parse-push-plugin` grab all my notifications for some reasons.

**Comment by salomari** [comment]
> parse-push-plugin

Does it work with Firebase?
