### ISSUE TITLE
Get data of notification

### ISSUE THREAD

**Issue by WillianAS** [fechanique/cordova-plugin-fcm#546]
Hi guys.
I have problem to get data form onNotification function.
The SO of device (IOS or Android) can get the information and mount the notification when app is on background. But if I try get de data and print with console.log(JSON.stringfy(data)) or alert(JSON.stringfy(data)).

`this.fcm.onNotification().subscribe(data => {
            if(data.wasTapped) {
                alert(JSON.stringify(data));
            } else {
                console.log(JSON.stringify(data));
            }
        });`

Return of console.log:
Object:
    wasTapped: false
    __proto__: Object

But nothing of title, message or something else.

Via the notification from API

`{
    "data": {
        "log": [
            {
                "success": true,
                "id": "XXXXXXXXXXXXX",
                "type": "accountId",
                "title": "título teste",
                "message": "teste 3 - 19/09",
                "status": "Id da notificação: 49"
            }
        ],
        "uuidLog": "XXXXXXXXXXXXX"
    },
    "message": null
}`

Ionic:
   ionic (Ionic CLI)  : 4.0.1 (C:\Users\Dell\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8
Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0, ios 4.4.0
System:
   Android SDK Tools : 26.1.1
   NodeJS            : v7.10.1 (C:\Program Files\nodejs\node.exe)
   npm               : 4.2.0
   OS                : Windows 10
Environment:
   ANDROID_HOME : C:\Android-sdk\android-sdk

**Comment by cayman1066** [comment]
This should take care of it for you:

From https://github.com/fechanique/cordova-plugin-fcm/issues/502

**Problem**
I had a really hard time finding out why, even though I was getting the notifications in the system's notification tray, all that happened when I clicked them was my app opening, but the onNotification callback was never being called.

**Solution**
The solution is actually really simple: just add "click_action":"FCM_PLUGIN_ACTIVITY" to your message when you are sending one to an Android device from your backend server using Firebase.

This will trigger the creation of the FCMPluginActivity (I still do not fully understand how this is achieved just by setting the click_action on the message, though), which then sends the push notification's playload to your application via the onNotification callback.

**Comment by WillianAS** [comment]
Thanks @cayman1066! I have done just like you say.
Can close this Issue
