### ISSUE TITLE
ios 11.4  FCMPlugin.onNotification not firing 

### ISSUE THREAD

**Issue by nissarcs** [fechanique/cordova-plugin-fcm#551]
I configured APNS in firebase cloud messaging console by uploading p8 file and team id and Key id . Application works perfectly in android but iOS  onNotification is not firing but messafe sent from server is successful . PLease look into this issue . Any help would be highly apprecaited

**Comment by nissarcs** [comment]
This issue with Xcode 10+ . Please use Xcode below 10 . App will work . I am closing this issue

**Comment by john-doherty** [comment]
Is there a workaround?
