### ISSUE TITLE
There's a push notification but when tapped nothing happend.

### ISSUE THREAD

**Issue by xgenem** [fechanique/cordova-plugin-fcm#554]
Hi I have the following code:
```
...
import { FCM } from '@ionic-native/fcm';

@Component({
  templateUrl: 'app.html',
})
export class App {
  @ViewChild('#myNav')
  nav: NavController;
  public rootPage: string = 'LandingPage'; // This needs to be updated once logged in / registered to be TabsPage
  public stylistParam: any;

  public lat: number;
  public long: number;

  constructor(
    platform: Platform,
    statusBar: StatusBar,
    ...
    public fcm: FCM
  ) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      ...
      this.checkAuthState();
    });
  }

  ...
  ...

  private checkAuthState() {
    console.log('checking auth state....');
    this.afAuth.authState.subscribe(res => {
      if (!res) {
        // Unauthenticated state
        this.rootPage = 'LandingPage';
      } else {
        const uid = res.uid;
        
        // register token
        this.fcm.getToken().then(token => {
          this.user.registerToken(token, uid);
        });

        this.fcm.subscribeToTopic('all');

        this.fcm.onNotification().subscribe(data => {
          console.log(`Data in notification ${data}`);
        })

        ....
        });
      }
    });
  }
}

```

But seriously nothing is happening. I should at least see some output from ```console.log(`Data in notification ${data}`);```

I'm using Ionic.

**Comment by CMGeldenhuys** [comment]
Did you manage to get your code working? We are having the same problem and I suspect it has to do with the new version of FCM. As the payload structure has been changed and for `click_action : 'FCM_PLUGIN_ACTIVITY` to work it needs to be placed inside `webpush: {...}` in the payload. Like in this post from the firebase team: [https://firebase.googleblog.com/2018/05/web-notifications-api-support-now.html](url).

**Comment by xgenem** [comment]
Hi @ccc2901! It turned out that the requirement wasn't really particular so I changed my approach. I added a basic function that handles the tapping and that's just it.

**Comment by SantoshTirukkovilour** [comment]
Hi @xgenem , Im facing with same issue, could you share your solution

**Comment by xgenem** [comment]
I wish I can help you immediately @SantoshTirukkovilour! I have removed the project already. If I have free time in the next few days I will definitely share my approach.

Thank you and sorry!
