### ISSUE TITLE
iOS foreground notification not fire event

### ISSUE THREAD

**Issue by jffs** [fechanique/cordova-plugin-fcm#565]
Hi, I use this plugin with Android and iOS.  On Android works perfectly but in iOS the event .onNotification() is not fired on foreground, yes in background.

I see the logs in XCode and when I send a notificacion and the app is opened i get this `Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.`

Any idea? I tested it using an iPhone 5.

**Comment by CharlieIGG** [comment]
@jffs did you fix this? Can you give a hint to us people facing the same issue?

**Comment by jffs** [comment]
> @jffs did you fix this? Can you give a hint to us people facing the same issue?


yes! but i dont know if it will be usefull for you. I'd also had local Notification plugin installed. Deleting that plugin gives me the possibility to handle push notification in foreground

**Comment by kapilSoni101** [comment]
@jffs - sir are u fixed above issue after remove local notification plugin?

**Comment by jffs** [comment]
Hey @kapilSoni101 ! Yes, after deleting Local Notifications Plugin i get it works. I dont know the situación of the issue nowadays.

**Comment by kapilSoni101** [comment]
@jffs- ok sir I will check and let u know
