### ISSUE TITLE
Push notification on click not working when app is closed android and iOS

### ISSUE THREAD

**Issue by cyberformed** [fechanique/cordova-plugin-fcm#571]
Push notification on click not working if the app has been closed on android and iOS.

Used the codes as per the documentation and have used 
`"click_action" : "FCM_PLUGIN_ACTIVITY"`
But still no luck.

Using `click_action` notification click works if the app is in background, bu not if the app has been closed.

Needs help in this regard.

**Comment by dexterprabhakar** [comment]
please show the console logs when app is closed

**Comment by cyberformed** [comment]
Now it's working. I have figured it out myself by sending `FCM_ACTIVITY` as the another `Key => Value` pair in the data payload for firebase.

**Comment by dexterprabhakar** [comment]
are u able to get notification callback in js ?. you will need that if u have to work on data sent in notification.

**Comment by ash737** [comment]
Hi @cyberformed 
I have same issue
Can I know how you fixed please?
