### ISSUE TITLE
Error: E/Zygote: isWhitelistProcess - Process is Whitelisted

### ISSUE THREAD

**Issue by Delfino65** [fechanique/cordova-plugin-fcm#587]
My app  crash with  Error E/Zygote: isWhitelistProcess - Process is Whitelisted. Anyone can help me?
cli packages:
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : 6.4.0 

local packages:
    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.0.0
    Ionic Framework    : ionic-angular 3.8.0

System:
    Node : v10.15.3
    npm  : 6.4.1 
    OS   : macOS

**Comment by alexandraat** [comment]
Did you find a answer?

**Comment by yasineryigit** [comment]
I'm looking for it too :/

**Comment by tahamiskini** [comment]
Same here
