### ISSUE TITLE
Android Bot in notification tray instead of launcher icon

### ISSUE THREAD

**Issue by dhavalkshah** [fechanique/cordova-plugin-fcm#594]
I have been able to achieve the notifications landing on the device and app being triggered (with data like title, body, custom, etc.)

But whenever the notification is delivered the notification icon is displayed as android bot. like 

![image](https://user-images.githubusercontent.com/9916703/59410552-bf173e00-8dd6-11e9-82d0-9a9c563dbd35.png)

My Launcher icon is a different icon, which works fine

To initiate the notification, I send a curl request to https://fcm.googleapis.com/fcm/send with the following json:

```
{ 
    "to":"device_token",
    "priority":"high",
    "notification":{ 
        "title":"New Notification!", 
        "body":"Test", 
        "sound":"default", 
        "click_action":"FCM_PLUGIN_ACTIVITY", 
        "icon": "icon" //optional piece 
    }, 
}
```

A icon.png is present in all `android/res/mipmap*` directories.

Also, I have added the following meta in my AndroidManifest.xml [reference](https://stackoverflow.com/questions/37325051/notification-icon-with-the-new-firebase-cloud-messaging-system)
`
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/icon" />`

Also, I have tried to read logcat from the device. Whenever I have passed icon param in the json that I post to fcm, I see the following log

`06-12 23:43:38.457 22257 22303 W FirebaseMessaging: Icon resource icon not found. Notification will use default icon.`

But whenever I don't pass the icon in the json, I dont see the above message in logcat.

I think I am missing a simple thing somewhere but not able to figure it out Please help me with some pointers, guidance on where i may be wrong

Thanks in advance

**Comment by marcgfx** [comment]
mipmap should work, I changed it to android:icon="@drawable/icon" though, as I misplaced my files

I am currently using

        <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="immo" />
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification" />
        <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/notify" />

in strings.xml I've added

        <color name="notify" type="color">#00963F</color>

I don't have any icon information in my push data, it just uses the defaults
and it works well, good luck

**Comment by dhavalkshah** [comment]
Thanks @marcgfx  for the input.
But the issue seems to be with firebase version 11.8.0
Here is the [reference](https://stackoverflow.com/questions/48137775/fcm-default-icon-uses-invalid-gradient/48414248) 

I had to change the FCMPlugin.gradle and project.properties to point to 11.0.1 instead of 11.8.0
Rebuild the android app and was able to receive the icon

**Comment by devner007** [comment]
I am using the [FCM plugin](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated) and here is what worked for me (September 2019):
1.  In **config.xml** (yourapp/config.xml)
Add the following to the <widget id=""...> tag at the end
`xmlns:android="http://schemas.android.com/apk/res/android"`

It should look something like this now:

`<widget id="com.mydomain.app" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:android="http://schemas.android.com/apk/res/android">`

Or simply, copy the above line, replace the value of widget id, with your own.

2. In the same **config.xml** file:
Just before the </platform> tag corresponding to <platform name="android">, add this:

```
<config-file parent="/manifest/application/" target="app/src/main/AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/fcm_push_icon" />
</config-file>
```
3. Visit the following link:
[Notification Icon Generator](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=1&source.space.pad=0&name=fcm_push_icon)

Upload a **White version (single color) of your logo on a Transparent background**. If you upload a colored version, you will get a dark gray icon, which would look nasty. If you don't have a white version of your logo, get it designed. Leave the rest of the settings as they are. For the Name textbox value, enter: **fcm_push_icon**. Then click on the Blue colored round shaped button to download the zip file. 

4. Unzip the zip file that you just downloaded it the above step and extract its contents to a folder. You will notice that it contains a **res** folder. If you open this folder, it will contain other folders with the following names:

- drawable-hdpi
- drawable-mdpi
- drawable-xhdpi
- drawable-xxhdpi
- drawable-xxxhdpi

Each of those folders will contain a PNG icon by the name "fcm_push_icon.png". The only difference between the icons in those different folders is their size. 

5. Open the following file path in your app (If it doesn't exist, create it as shown below):

`yourApp/platforms/android/app/src/main/res`

Simply copy all the 5 folders listed in in the point 4 above, to the location shown just above i.e. into the **res** folder i.e. into `yourApp/platforms/android/app/src/main/res`

That's it! Now just build your app. Whenever you receive a notification, you will see your app icon in the notifications (at least on Android).

**_If anyone has figured out how to make colored icons appear in the Android notifications, please share your solution._**
