### ISSUE TITLE
Android - FCMPlugin.onNotification not called with data

### ISSUE THREAD

**Issue by camden-kid** [fechanique/cordova-plugin-fcm#64]
I have successfully installed the plugin in my project and everything is working well except for the final part, meaning receiving a notification in the Android emulator.

The console shows the message
> onNotification callback successfully registered

and the console displays the token from FCMPlugin.getToken, which looks okay

This is the data I send from my server

```
url: 'https://fcm.googleapis.com/fcm/send',
method: 'POST',
headers: {
    "Content-Type": "application/json",
    "Authorization": "key=XXXXXXXXXXXXXXXXXXXXX" // Server key
},
json: {
    "to" : req.body.id, // token
    "priority" : "high",
    "notification": {
        "title": "Portugal vs. Denmark",
        "body": "5 to 1",
        "sound":"default",
        "click_action":"FCM_PLUGIN_ACTIVITY",
        "icon":"fcm_push_icon"
    },
    "data":{
        "param1":"value1",
        "param2":"value2"
    }
}

```

This is the output I see from the server when it POSTs the data

> { multicast_id: 7199059114687358000,
>   success: 1,
>   failure: 0,
>   canonical_ids: 0,
>   results: [ { message_id: '0:1470476355620770%65a7acc165a7acc1' } ] }

I haven't created a fcm_push_icon but I imagine that's not the cause of the problem.

An error I am seeing in the console is this:

![image](https://cloud.githubusercontent.com/assets/890197/17457036/f094ed0c-5be2-11e6-8402-ce7e66659ac6.png)

Could that be the cause? Any suggestions would be appreciated.

**Comment by camden-kid** [comment]
Turns out the EvalError was the reason why I wasn't seeing the data. To fix this I changed the Content-Security-Policy in index.html from

    meta(http-equiv="Content-Security-Policy", content="default-src * 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data:")

to

    meta(http-equiv="Content-Security-Policy", content="default-src * 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data:")

I'm still not getting the notification but data in FCMPlugin.onNotification is

    {
        "param1":"value1",
        "param2":"value2"
    }

which will do for the moment.

**Comment by GitFr33** [comment]
I have the same issue. I would prefer not use 'unsafe-eval' if possible.

From looking at https://issues.apache.org/jira/browse/CB-9277 it seems that this is caused using by depreciated API:

> The deprecated function on the Java side is:
> https://github.com/apache/cordova-android/blob/4bf705a3d39b34400388265381a9975b246e3779/framework/src/org/apache/cordova/CordovaWebView.java#L92
> There's really no way to support this method that works with without unsafe-eval. I think the best course of action is to leave it in (and deprecated) for a while longer until plugins stop using (they should stop since it is now broken by default).

Am I understanding the situation correctly?

**Comment by camden-kid** [comment]
@GitFr33  I don't know much about this so I can't say unfortunately.
