### ISSUE TITLE
Does it really need: Android Support Repository version 20 or greater

### ISSUE THREAD

**Issue by mburger81** [fechanique/cordova-plugin-fcm#76]
In the Android SDK Manager, **Android Support Library** is declared as obsolete, so my question is:
Does it really need?

![image](https://cloud.githubusercontent.com/assets/3778892/17775546/f9f975fa-6558-11e6-9c48-90b6ae2f5411.png)

**Comment by fechanique** [comment]
I need to check that

**Comment by acailly** [comment]
Just did that:
- made it work with Android Support Library
- deleted it
- it still works

So I think it is not required

**Comment by mburger81** [comment]
For now we are not using the plugin, so we will check this in feature and will reopen a new issue if it persist.

Thx you all
