### ISSUE TITLE
Cordova-plugin-fcm FCMPlugin notification toast while in background

### ISSUE THREAD

**Issue by blademeld** [fechanique/cordova-plugin-fcm#77]
I posted this on stackoverflow first (http://stackoverflow.com/questions/39016336/cordova-plugin-fcm-fcmplugin-notification-toast-while-in-background) but I guess I should have come here first.

I'm using https://github.com/fechanique/cordova-plugin-fcm for a project at the moment and I was wondering if there was a way for a cordova application running in the background to:

a. show a toast popup when notifications arrive. (not just in the notification bar but an alert toast in the middle of the screen)

b. wake up the screen if the screen if the screen has been turned off.

c. change the color of the toast/notification via the cordova plugin

for both android and iOS.

if it's not possible to do it via stock plugin, is there a easy config file in the plugin?

Thanks in advance

**Comment by ricardojlrufino** [comment]
set the notification icon background color you just need to pass a key as **"color": "#RRGGBB"** format. Check the android key references in this link .
https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by blademeld** [comment]
Thanks man, I thought it was an option in the plugin itself and didn't think to check the request JSON API.

**Comment by nurfgun** [comment]
Man. I've spent several days on those questions with no luck. Have you found any satisfying answers to them?

**Comment by blademeld** [comment]
I don't recall why I left this open. I finished the project a couple months after this. The customer was satisfied with whatever level Cordova was able to provide without further modification than what ricardojlrufino suggested and I haven't looked into Cordova after that. Sorry about that nurfgun, I don't even recall if the other requests were completed with Cordova or not.
