### ISSUE TITLE
Android 6 not receiving notifications when app is not running

### ISSUE THREAD

**Issue by tisho91** [fechanique/cordova-plugin-fcm#81]
I'm using this plugin and testing on my android marshmallow, but when app is not running(or closed) the notifications are not received. I've tested it with another android device (kitkat) and it seems fine. Can I fix that and how? Because the idea is to remind users to open the app if they didn't for the day.

**Comment by lveigas** [comment]
Hi tisho91,

I'm having the same problem. How did you solved it?

Thanks and Best Regards,
Luís
