### ISSUE TITLE
Couldn't find GoogleService-Info.plist

### ISSUE THREAD

**Issue by Hurinj** [fechanique/cordova-plugin-fcm#85]
Hello,

I downloaded the plist in my firebase project and put it in my root folder.
When I launch my app I get :

HelloCordova[2207:612538] Could not locate configuration file: 'GoogleService-Info.plist'.
Terminating app due to uncaught exception 'com.firebase.core', reason: '[FIRApp configure] could not find a valid GoogleServices-Info.plist in your project. Please download one from https://console.firebase.google.com/.'

Any idea ?
The instruction says "You will need 2 generated files in the Firebase configuration process" I don't get it. Moreover I don't have Android version on firebase, I only want it for iOS

**Comment by newapx** [comment]
You must copy file 'GoogleService-Info.plist' in folder 'Resources' (directly in XCode)

**Comment by gidkom** [comment]
Hello, Is there a way to do this via hooks? thanks.

**Comment by fechanique** [comment]
I'm going to update this soon
