### ISSUE TITLE
How to subscribe other user(s) from current user's client device?

### ISSUE THREAD

**Issue by bmwertman** [fechanique/cordova-plugin-fcm#96]
I'm creating a chat app and users can create one-on-one or group chats with other users. 

When a user creates a chat room I need the user or users they have added to the chat room to be subscribed to a room topic that will receive push notifications when someone adds a new message to the room.

Is subscribing another client app from the current client app possible?

**Comment by bmwertman** [comment]
Nevermind, I was able to handle this through topic subscriptions.

**Comment by siphiwe** [comment]
Hi @bmwertman Could you please explain how you handled this through topic subscriptions? I'm struggling to figure out how to subscribe users to multiple topics. Do you do it using the plugin or outside? Is it a once-off subscription or do you do it each time the app initialises?
